// AUTO-GENERATED by scripts/_audit/gen_misc.cjs (2026-08-26)
// 域: base ｜ 来源: live information_schema ｜ 建模 1 张核心缺失表。
// 导出名冲突自动规避（追加 Gen 后缀）；跨域 FK 注释保留；内部/已建模 FK 实写。
import { mysqlTable, int, bigint, smallint, mediumint, tinyint, varchar, char, decimal, float, double, text, date, datetime, timestamp, time, json, mysqlEnum, primaryKey, index, uniqueIndex, foreignKey } from 'drizzle-orm/mysql-core';
import { sql } from 'drizzle-orm';

export const baseInk = mysqlTable('base_ink', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  inkCode: varchar('ink_code', { length: 50 }).notNull(),
  inkName: varchar('ink_name', { length: 200 }).notNull(),
  colorCode: varchar('color_code', { length: 50 }),
  colorName: varchar('color_name', { length: 100 }),
  inkType: varchar('ink_type', { length: 20 }),
  supplierId: bigint('supplier_id', { mode: 'number', unsigned: true }),
  supplierName: varchar('supplier_name', { length: 200 }),
  specification: varchar('specification', { length: 200 }),
  unit: varchar('unit', { length: 20 }),
  unitPrice: decimal('unit_price', { precision: 18, scale: 4 }),
  stockQty: decimal('stock_qty', { precision: 18, scale: 4 }).default('0.0000'),
  minStock: decimal('min_stock', { precision: 18, scale: 4 }).default('0.0000'),
  status: tinyint('status').default(1),
  remark: text('remark'),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
  createBy: bigint('create_by', { mode: 'number', unsigned: true }),
  deleted: tinyint('deleted').default(0),
}, (t) => ({
  idxInkType: index('idx_ink_type').on(t.inkType),
  idxSupplier: index('idx_supplier').on(t.supplierId),
  pk: primaryKey({ columns: [t.id] }),
  ukInkCode: uniqueIndex('uk_ink_code').on(t.inkCode),
}));

