// AUTO-GENERATED by scripts/_audit/gen_misc.cjs (2026-08-26)
// 域: eq ｜ 来源: live information_schema ｜ 建模 3 张核心缺失表。
// 导出名冲突自动规避（追加 Gen 后缀）；跨域 FK 注释保留；内部/已建模 FK 实写。
import { mysqlTable, int, bigint, tinyint, varchar, decimal, text, date, datetime, json, primaryKey, index, uniqueIndex, foreignKey } from 'drizzle-orm/mysql-core';
import { sql } from 'drizzle-orm';







