// AUTO-GENERATED by scripts/_audit/gen_misc.cjs (2026-08-26)
// 域: qr ｜ 来源: live information_schema ｜ 建模 1 张核心缺失表。
// 导出名冲突自动规避（追加 Gen 后缀）；跨域 FK 注释保留；内部/已建模 FK 实写。
import { mysqlTable, int, bigint, smallint, mediumint, tinyint, varchar, char, decimal, float, double, text, date, datetime, timestamp, time, json, mysqlEnum, primaryKey, index, uniqueIndex, foreignKey } from 'drizzle-orm/mysql-core';
import { sql } from 'drizzle-orm';

export const qrCodeRecord = mysqlTable('qr_code_record', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  qrCode: varchar('qr_code', { length: 100 }).notNull(),
  contentType: varchar('content_type', { length: 20 }),
  contentData: text('content_data'),
  materialId: bigint('material_id', { mode: 'number', unsigned: true }),
  materialCode: varchar('material_code', { length: 50 }),
  batchNo: varchar('batch_no', { length: 50 }),
  status: tinyint('status').default(1),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
}));

