// AUTO-GENERATED by scripts/_audit/gen_misc.cjs (2026-08-26)
// 域: mdm ｜ 来源: live information_schema ｜ 建模 1 张核心缺失表。
// 导出名冲突自动规避（追加 Gen 后缀）；跨域 FK 注释保留；内部/已建模 FK 实写。
import { mysqlTable, int, bigint, smallint, mediumint, tinyint, varchar, char, decimal, float, double, text, date, datetime, timestamp, time, json, mysqlEnum, primaryKey, index, uniqueIndex, foreignKey } from 'drizzle-orm/mysql-core';
import { sql } from 'drizzle-orm';

export const mdmProduct = mysqlTable('mdm_product', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  productCode: varchar('product_code', { length: 50 }).notNull(),
  productName: varchar('product_name', { length: 200 }).notNull(),
  shortName: varchar('short_name', { length: 100 }).default(''),
  specification: varchar('specification', { length: 200 }).default(''),
  unit: varchar('unit', { length: 20 }).default('件'),
  categoryId: bigint('category_id', { mode: 'number', unsigned: true }),
  categoryName: varchar('category_name', { length: 100 }).default(''),
  customerId: bigint('customer_id', { mode: 'number', unsigned: true }),
  customerName: varchar('customer_name', { length: 100 }).default(''),
  bomVersion: varchar('bom_version', { length: 20 }).default('V1.0'),
  description: text('description'),
  status: varchar('status', { length: 20 }).default('active'),
  costPrice: decimal('cost_price', { precision: 12, scale: 2 }).default('0.00'),
  salePrice: decimal('sale_price', { precision: 12, scale: 2 }).default('0.00'),
  minStock: decimal('min_stock', { precision: 12, scale: 2 }).default('0.00'),
  maxStock: decimal('max_stock', { precision: 12, scale: 2 }).default('0.00'),
  safetyStock: decimal('safety_stock', { precision: 12, scale: 2 }).default('0.00'),
  deleted: tinyint('deleted').default(0),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  idxCategory: index('idx_category').on(t.categoryId),
  idxCustomer: index('idx_customer').on(t.customerId),
  idxStatus: index('idx_status').on(t.status),
  pk: primaryKey({ columns: [t.id] }),
  ukProductCode: uniqueIndex('uk_product_code').on(t.productCode),
}));

