import { purSupplier } from './procurement';
import { crmCustomer } from './_gen_crm';
// AUTO-GENERATED by scripts/_audit/gen_fin.cjs (2026-08-26)
// 来源: live information_schema. 建模 9 张核心 fin_* 缺失表。
// 跨域 FK / 自引用 FK 以注释保留；内部 fin_* FK 实写。
import { mysqlTable, int, bigint, smallint, mediumint, tinyint, varchar, char, decimal, float, double, text, date, datetime, timestamp, time, json, mysqlEnum, primaryKey, index, uniqueIndex, foreignKey } from 'drizzle-orm/mysql-core';
import { sql } from 'drizzle-orm';

export const finAccount = mysqlTable('fin_account', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  accountCode: varchar('account_code', { length: 20 }).notNull(),
  accountName: varchar('account_name', { length: 100 }).notNull(),
  fullName: varchar('full_name', { length: 200 }),
  parentId: bigint('parent_id', { mode: 'number', unsigned: true }),
  level: tinyint('level').default(1),
  accountType: tinyint('account_type').notNull(),
  balanceDirection: tinyint('balance_direction').notNull(),
  isLeaf: tinyint('is_leaf').default(1),
  assistTypes: varchar('assist_types', { length: 200 }),
  status: tinyint('status').default(1),
  sortOrder: int('sort_order').default(0),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
  createBy: bigint('create_by', { mode: 'number', unsigned: true }),
  updateBy: bigint('update_by', { mode: 'number', unsigned: true }),
  deleted: tinyint('deleted').notNull().default(0),
}, (t) => ({
  idxParent: index('idx_parent').on(t.parentId),
  idxType: index('idx_type').on(t.accountType),
  pk: primaryKey({ columns: [t.id] }),
  ukAccountCode: uniqueIndex('uk_account_code').on(t.accountCode),
}));

export const finCostRecord = mysqlTable('fin_cost_record', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  costNo: varchar('cost_no', { length: 50 }).notNull(),
  costType: varchar('cost_type', { length: 50 }).default(''),
  costCategory: varchar('cost_category', { length: 50 }).default(''),
  costDate: date('cost_date'),
  amount: decimal('amount', { precision: 12, scale: 2 }).default('0.00'),
  orderNo: varchar('order_no', { length: 50 }).default(''),
  productName: varchar('product_name', { length: 200 }).default(''),
  department: varchar('department', { length: 100 }).default(''),
  description: text('description'),
  status: tinyint('status').default(0),
  remark: text('remark'),
  deleted: tinyint('deleted').default(0),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  idxCostDate: index('idx_cost_date').on(t.costDate),
  idxCostType: index('idx_cost_type').on(t.costType),
  pk: primaryKey({ columns: [t.id] }),
  ukCostNo: uniqueIndex('uk_cost_no').on(t.costNo),
}));

export const finPaymentRecord = mysqlTable('fin_payment_record', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  paymentNo: varchar('payment_no', { length: 50 }).notNull(),
  payableId: bigint('payable_id', { mode: 'number', unsigned: true }),
  supplierId: bigint('supplier_id', { mode: 'number', unsigned: true }),
  amount: decimal('amount', { precision: 18, scale: 4 }).default('0.0000'),
  paymentMethod: varchar('payment_method', { length: 20 }),
  paymentDate: date('payment_date'),
  remark: text('remark'),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  deleted: tinyint('deleted').default(0),
}, (t) => ({
  idxPayable: index('idx_payable').on(t.payableId),
  idxSupplier: index('idx_supplier').on(t.supplierId),
  pk: primaryKey({ columns: [t.id] }),
}));

export const finPeriod = mysqlTable('fin_period', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  periodCode: varchar('period_code', { length: 10 }).notNull(),
  periodName: varchar('period_name', { length: 20 }),
  startDate: date('start_date').notNull(),
  endDate: date('end_date').notNull(),
  isClosed: tinyint('is_closed').default(0),
  status: tinyint('status').default(0),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
  createBy: bigint('create_by', { mode: 'number', unsigned: true }),
  updateBy: bigint('update_by', { mode: 'number', unsigned: true }),
  deleted: tinyint('deleted').notNull().default(0),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
  ukPeriodCode: uniqueIndex('uk_period_code').on(t.periodCode),
}));

export const finReceiptRecord = mysqlTable('fin_receipt_record', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  receiptNo: varchar('receipt_no', { length: 50 }).notNull(),
  receivableId: bigint('receivable_id', { mode: 'number', unsigned: true }),
  customerId: bigint('customer_id', { mode: 'number', unsigned: true }),
  amount: decimal('amount', { precision: 18, scale: 4 }).default('0.0000'),
  paymentMethod: varchar('payment_method', { length: 20 }),
  receiptDate: date('receipt_date'),
  remark: text('remark'),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  deleted: tinyint('deleted').default(0),
}, (t) => ({
  idxCustomer: index('idx_customer').on(t.customerId),
  idxReceivable: index('idx_receivable').on(t.receivableId),
  pk: primaryKey({ columns: [t.id] }),
}));

export const finReceivableLine = mysqlTable('fin_receivable_line', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  receivableId: bigint('receivable_id', { mode: 'number', unsigned: true }).notNull(),
  lineNo: int('line_no'),
  salesOrderId: bigint('sales_order_id', { mode: 'number', unsigned: true }),
  salesOrderNo: varchar('sales_order_no', { length: 50 }),
  invoiceNo: varchar('invoice_no', { length: 50 }),
  amount: decimal('amount', { precision: 12, scale: 2 }),
  taxAmount: decimal('tax_amount', { precision: 12, scale: 2 }),
  totalAmount: decimal('total_amount', { precision: 12, scale: 2 }),
  status: tinyint('status').default(1),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
}));

export const finAccountBalance = mysqlTable('fin_account_balance', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  periodCode: varchar('period_code', { length: 10 }).notNull(),
  accountId: bigint('account_id', { mode: 'number', unsigned: true }).notNull(),
  accountCode: varchar('account_code', { length: 20 }),
  beginDebit: decimal('begin_debit', { precision: 18, scale: 4 }).default('0.0000'),
  beginCredit: decimal('begin_credit', { precision: 18, scale: 4 }).default('0.0000'),
  currentDebit: decimal('current_debit', { precision: 18, scale: 4 }).default('0.0000'),
  currentCredit: decimal('current_credit', { precision: 18, scale: 4 }).default('0.0000'),
  yearDebit: decimal('year_debit', { precision: 18, scale: 4 }).default('0.0000'),
  yearCredit: decimal('year_credit', { precision: 18, scale: 4 }).default('0.0000'),
  endDebit: decimal('end_debit', { precision: 18, scale: 4 }).default('0.0000'),
  endCredit: decimal('end_credit', { precision: 18, scale: 4 }).default('0.0000'),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
  createBy: bigint('create_by', { mode: 'number', unsigned: true }),
  updateBy: bigint('update_by', { mode: 'number', unsigned: true }),
  deleted: tinyint('deleted').notNull().default(0),
}, (t) => ({
  idxAccount: index('idx_account').on(t.accountId),
  pk: primaryKey({ columns: [t.id] }),
  ukPeriodAccount: uniqueIndex('uk_period_account').on(t.periodCode, t.accountId),
  fkFinAccountBalanceAccount: foreignKey({ columns: [t.accountId], foreignColumns: [finAccount.id] }),
  fkFinAccountBalancePeriod: foreignKey({ columns: [t.periodCode], foreignColumns: [finPeriod.periodCode] }),
}));

export const finVoucher = mysqlTable('fin_voucher', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  voucherNo: varchar('voucher_no', { length: 50 }).notNull(),
  periodCode: varchar('period_code', { length: 10 }).notNull(),
  voucherDate: date('voucher_date').notNull(),
  voucherType: tinyint('voucher_type').notNull(),
  sourceType: varchar('source_type', { length: 50 }),
  sourceId: bigint('source_id', { mode: 'number', unsigned: true }),
  sourceNo: varchar('source_no', { length: 50 }),
  totalDebit: decimal('total_debit', { precision: 18, scale: 4 }).default('0.0000'),
  totalCredit: decimal('total_credit', { precision: 18, scale: 4 }).default('0.0000'),
  totalAmount: decimal('total_amount', { precision: 18, scale: 4 }).default('0.0000'),
  status: tinyint('status').default(0),
  summary: text('summary'),
  remark: varchar('remark', { length: 500 }),
  attachmentCount: int('attachment_count').default(0),
  deleted: tinyint('deleted').notNull().default(0),
  createBy: varchar('create_by', { length: 50 }),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  auditedBy: varchar('audited_by', { length: 50 }),
  auditedAt: datetime('audited_at'),
  postedBy: varchar('posted_by', { length: 50 }),
  postedAt: datetime('posted_at'),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
  updateBy: bigint('update_by', { mode: 'number', unsigned: true }),
}, (t) => ({
  idxPeriod: index('idx_period').on(t.periodCode),
  idxSource: index('idx_source').on(t.sourceType, t.sourceId),
  idxStatus: index('idx_status').on(t.status),
  pk: primaryKey({ columns: [t.id] }),
  ukVoucherNo: uniqueIndex('uk_voucher_no').on(t.voucherNo),
  fkFinVoucherPeriod: foreignKey({ columns: [t.periodCode], foreignColumns: [finPeriod.periodCode] }),
}));

// SKIP-FK (cross-domain): fin_voucher_line.customerId -> crm_customer.id [/]
// SKIP-FK (cross-domain): fin_voucher_line.supplierId -> pur_supplier.id [/]
export const finVoucherLine = mysqlTable('fin_voucher_line', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  voucherId: bigint('voucher_id', { mode: 'number', unsigned: true }).notNull(),
  lineNo: int('line_no').notNull(),
  accountId: bigint('account_id', { mode: 'number', unsigned: true }).notNull(),
  accountCode: varchar('account_code', { length: 20 }),
  accountName: varchar('account_name', { length: 100 }),
  summary: varchar('summary', { length: 500 }),
  debitAmount: decimal('debit_amount', { precision: 18, scale: 4 }).default('0.0000'),
  creditAmount: decimal('credit_amount', { precision: 18, scale: 4 }).default('0.0000'),
  debitAccount: varchar('debit_account', { length: 100 }),
  creditAccount: varchar('credit_account', { length: 100 }),
  amount: decimal('amount', { precision: 18, scale: 4 }).default('0.0000'),
  description: varchar('description', { length: 500 }),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  customerId: bigint('customer_id', { mode: 'number', unsigned: true }),
  supplierId: bigint('supplier_id', { mode: 'number', unsigned: true }),
  departmentId: int('department_id', { unsigned: true }),
  projectId: int('project_id', { unsigned: true }),
}, (t) => ({
  idxAccount: index('idx_account').on(t.accountId),
  idxCustomer: index('idx_customer').on(t.customerId),
  idxDepartment: index('idx_department').on(t.departmentId),
  idxProject: index('idx_project').on(t.projectId),
  idxSupplier: index('idx_supplier').on(t.supplierId),
  idxVoucher: index('idx_voucher').on(t.voucherId),
  pk: primaryKey({ columns: [t.id] }),
  fkFinVoucherLineAccount: foreignKey({ columns: [t.accountId], foreignColumns: [finAccount.id] }),
  fkVoucherLineVoucher: foreignKey({ columns: [t.voucherId], foreignColumns: [finVoucher.id] }),
    fk_crmCustomer_customerId: foreignKey({
      name: 'fk_fin_voucher_line_customer',
      columns: [t.customerId],
      foreignColumns: [crmCustomer.id],
    })
      .onDelete('set null')
      .onUpdate('cascade'),
    fk_purSupplier_supplierId: foreignKey({
      name: 'fk_fin_voucher_line_supplier',
      columns: [t.supplierId],
      foreignColumns: [purSupplier.id],
    })
      .onDelete('set null')
      .onUpdate('cascade'),
  }));

