// AUTO-GENERATED by scripts/_audit/gen_misc.cjs (2026-08-26)
// 域: qms ｜ 来源: live information_schema ｜ 建模 5 张核心缺失表。
// 导出名冲突自动规避（追加 Gen 后缀）；跨域 FK 注释保留；内部/已建模 FK 实写。
import { bigint, date, datetime, decimal, json, mysqlTable, primaryKey, text, tinyint, varchar } from 'drizzle-orm/mysql-core';
import { sql } from 'drizzle-orm';

export const qmsComplaint = mysqlTable('qms_complaint', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  complaintNo: varchar('complaint_no', { length: 50 }).notNull(),
  customerId: bigint('customer_id', { mode: 'number', unsigned: true }),
  customerName: varchar('customer_name', { length: 100 }),
  materialId: bigint('material_id', { mode: 'number', unsigned: true }),
  materialCode: varchar('material_code', { length: 50 }),
  materialName: varchar('material_name', { length: 200 }),
  complaintType: varchar('complaint_type', { length: 20 }),
  complaintDesc: text('complaint_desc'),
  complaintDate: date('complaint_date'),
  status: tinyint('status').default(0),
  handlerId: bigint('handler_id', { mode: 'number', unsigned: true }),
  handlerName: varchar('handler_name', { length: 50 }),
  remark: text('remark'),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  deleted: tinyint('deleted').notNull().default(0),
    closeTime: datetime('close_time'), // close_time
    complaintLevel: tinyint('complaint_level'), // complaint_level
    complaintSource: varchar('complaint_source', { length: 50 }), // complaint_source
    containAction: varchar('contain_action', { length: 100 }), // contain_action
    correctiveAction: varchar('corrective_action', { length: 100 }), // corrective_action
    createBy: varchar('create_by', { length: 100 }), // create_by
    d1Date: datetime('d1_date'), // D1 日期
    d1Team: varchar('d1_team', { length: 100 }), // D1 成立小组
    d2Date: datetime('d2_date'), // D2 日期
    d2Desc: text('d2_desc'), // D2 问题描述
    d3Date: datetime('d3_date'), // D3 日期
    d3InterimAction: varchar('d3_interim_action', { length: 500 }), // D3 临时措施
    d4Date: datetime('d4_date'), // D4 日期
    d4RootCause: varchar('d4_root_cause', { length: 500 }), // D4 根因
    d5CorrectiveAction: varchar('d5_corrective_action', { length: 500 }), // D5 纠正措施
    d5Date: datetime('d5_date'), // D5 日期
    d6Date: datetime('d6_date'), // D6 日期
    d6ImplementVerify: varchar('d6_implement_verify', { length: 500 }), // D6 实施验证
    d7Date: datetime('d7_date'), // D7 日期
    d7PreventiveAction: varchar('d7_preventive_action', { length: 500 }), // D7 预防措施
    d8Congratulations: varchar('d8_congratulations', { length: 500 }), // D8 团队祝贺
    d8Date: datetime('d8_date'), // D8 日期
    defectDate: datetime('defect_date'), // defect_date
    defectDesc: varchar('defect_desc', { length: 100 }), // defect_desc
    defectQty: decimal('defect_qty', { precision: 18, scale: 4 }).default('0.0000'), // defect_qty
    defectRate: decimal('defect_rate', { precision: 18, scale: 4 }).default('0.0000'), // defect_rate
    handler: varchar('handler', { length: 100 }), // handler
    orderNo: varchar('order_no', { length: 50 }), // order_no
    preventiveAction: varchar('preventive_action', { length: 50 }), // preventive_action
    productCode: varchar('product_code', { length: 50 }), // product_code
    productId: bigint('product_id', { mode: 'number', unsigned: true }), // product_id
    productName: varchar('product_name', { length: 50 }), // product_name
    reportDate: datetime('report_date'), // report_date
    reportTime: datetime('report_time'), // report_time
    reporter: varchar('reporter', { length: 50 }), // reporter
    rootCause: varchar('root_cause', { length: 100 }), // root_cause
    severity: tinyint('severity'), // severity
    totalQty: decimal('total_qty', { precision: 18, scale: 4 }).default('0.0000'), // total_qty
    verifier: varchar('verifier', { length: 100 }), // verifier
    verifyResult: tinyint('verify_result'), // verify_result
    verifyTime: datetime('verify_time'), // verify_time
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
}));

export const qmsLabTest = mysqlTable('qms_lab_test', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  testNo: varchar('test_no', { length: 50 }).notNull(),
  materialId: bigint('material_id', { mode: 'number', unsigned: true }),
  materialCode: varchar('material_code', { length: 50 }),
  materialName: varchar('material_name', { length: 200 }),
  testType: varchar('test_type', { length: 20 }),
  testItems: varchar('test_items', { length: 500 }),
  testMethod: varchar('test_method', { length: 200 }),
  testDate: date('test_date'),
  testResult: varchar('test_result', { length: 20 }),
  status: tinyint('status').default(1),
  testerId: bigint('tester_id', { mode: 'number', unsigned: true }),
  testerName: varchar('tester_name', { length: 50 }),
  remark: text('remark'),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  deleted: tinyint('deleted').notNull().default(0),
    acceptQty: decimal('accept_qty', { precision: 18, scale: 4 }).default('0.0000'), // accept_qty
    aqlLevel: tinyint('aql_level'), // aql_level
    batchNo: varchar('batch_no', { length: 50 }), // batch_no
    conclusion: varchar('conclusion', { length: 100 }), // conclusion
    createBy: varchar('create_by', { length: 100 }), // create_by
    detailData: json('detail_data'), // detail_data
    equipmentUsed: varchar('equipment_used', { length: 255 }), // equipment_used
    inspectionId: bigint('inspection_id', { mode: 'number', unsigned: true }), // inspection_id
    inspectionStandard: varchar('inspection_standard', { length: 100 }), // inspection_standard
    inspectionType: tinyint('inspection_type'), // inspection_type
    labTestNo: varchar('lab_test_no', { length: 50 }), // lab_test_no
    overallResult: tinyint('overall_result'), // overall_result
    productCode: varchar('product_code', { length: 50 }), // product_code
    productId: bigint('product_id', { mode: 'number', unsigned: true }), // product_id
    productName: varchar('product_name', { length: 50 }), // product_name
    rejectQty: decimal('reject_qty', { precision: 18, scale: 4 }).default('0.0000'), // reject_qty
    resultSummary: tinyint('result_summary'), // result_summary
    reviewTime: datetime('review_time'), // review_time
    reviewer: varchar('reviewer', { length: 100 }), // reviewer
    sampleSize: decimal('sample_size', { precision: 18, scale: 4 }).default('0.0000'), // sample_size
    sampleSource: varchar('sample_source', { length: 50 }), // sample_source
    testEquipment: varchar('test_equipment', { length: 255 }), // test_equipment
    testStandard: varchar('test_standard', { length: 100 }), // test_standard
    testTime: datetime('test_time'), // test_time
    tester: varchar('tester', { length: 100 }), // tester
    updateTime: datetime('update_time'), // update_time
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
}));

export const qmsSgsCert = mysqlTable('qms_sgs_cert', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  certNo: varchar('cert_no', { length: 50 }).notNull(),
  materialId: bigint('material_id', { mode: 'number', unsigned: true }),
  materialCode: varchar('material_code', { length: 50 }),
  materialName: varchar('material_name', { length: 200 }),
  supplierId: bigint('supplier_id', { mode: 'number', unsigned: true }),
  supplierName: varchar('supplier_name', { length: 200 }),
  certType: varchar('cert_type', { length: 20 }),
  testItems: varchar('test_items', { length: 500 }),
  testResult: varchar('test_result', { length: 20 }),
  testReportNo: varchar('test_report_no', { length: 50 }),
  testOrg: varchar('test_org', { length: 100 }),
  issueDate: date('issue_date'),
  expireDate: date('expire_date'),
  status: tinyint('status').default(1),
  fileUrl: varchar('file_url', { length: 500 }),
  remark: text('remark'),
  deleted: tinyint('deleted').default(0),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
}));

export const qmsSgsCertItem = mysqlTable('qms_sgs_cert_item', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  certId: bigint('cert_id', { mode: 'number', unsigned: true }).notNull(),
  itemName: varchar('item_name', { length: 100 }).notNull(),
  limitValue: varchar('limit_value', { length: 50 }),
  testValue: varchar('test_value', { length: 50 }),
  result: varchar('result', { length: 20 }),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  deleted: tinyint('deleted').notNull().default(0),
    sortOrder: varchar('sort_order', { length: 50 }), // sort_order
    testItemName: varchar('test_item_name', { length: 100 }), // test_item_name
    testStandard: varchar('test_standard', { length: 100 }), // test_standard
    unit: varchar('unit', { length: 100 }), // unit
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
}));

export const qmsSupplierAudit = mysqlTable('qms_supplier_audit', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  auditNo: varchar('audit_no', { length: 50 }).notNull(),
  supplierId: bigint('supplier_id', { mode: 'number', unsigned: true }),
  supplierCode: varchar('supplier_code', { length: 50 }),
  supplierName: varchar('supplier_name', { length: 200 }),
  auditType: varchar('audit_type', { length: 20 }),
  auditDate: date('audit_date'),
  auditResult: varchar('audit_result', { length: 20 }),
  status: tinyint('status').default(1),
  auditorId: bigint('auditor_id', { mode: 'number', unsigned: true }),
  auditorName: varchar('auditor_name', { length: 50 }),
  remark: text('remark'),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  deleted: tinyint('deleted').notNull().default(0),
    auditItems: varchar('audit_items', { length: 100 }), // audit_items
    auditScope: varchar('audit_scope', { length: 100 }), // audit_scope
    auditScores: decimal('audit_scores', { precision: 18, scale: 4 }).default('0.0000'), // audit_scores
    auditor: varchar('auditor', { length: 100 }), // auditor
    conclusion: varchar('conclusion', { length: 100 }), // conclusion
    correctiveRequest: varchar('corrective_request', { length: 100 }), // corrective_request
    createBy: varchar('create_by', { length: 100 }), // create_by
    deadline: varchar('deadline', { length: 100 }), // deadline
    deliveryScore: decimal('delivery_score', { precision: 18, scale: 4 }).default('0.0000'), // delivery_score
    followUpDate: datetime('follow_up_date'), // follow_up_date
    improvementItems: varchar('improvement_items', { length: 50 }), // improvement_items
    nonconformities: varchar('nonconformities', { length: 50 }), // nonconformities
    priceScore: decimal('price_score', { precision: 18, scale: 4 }).default('0.0000'), // price_score
    qualitySystemScore: decimal('quality_system_score', { precision: 18, scale: 4 }).default('0.0000'), // quality_system_score
    serviceScore: decimal('service_score', { precision: 18, scale: 4 }).default('0.0000'), // service_score
    totalScore: decimal('total_score', { precision: 18, scale: 4 }).default('0.0000'), // total_score
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
}));

