// AUTO-GENERATED by scripts/_audit/gen_misc.cjs (2026-08-26)
// 域: eng ｜ 来源: live information_schema ｜ 建模 2 张核心缺失表。
// 导出名冲突自动规避（追加 Gen 后缀）；跨域 FK 注释保留；内部/已建模 FK 实写。
import { mysqlTable, int, bigint, smallint, mediumint, tinyint, varchar, char, decimal, float, double, text, date, datetime, timestamp, time, json, mysqlEnum, primaryKey, index, uniqueIndex, foreignKey } from 'drizzle-orm/mysql-core';
import { sql } from 'drizzle-orm';

export const engSampleToMass = mysqlTable('eng_sample_to_mass', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  sampleOrderId: bigint('sample_order_id', { mode: 'number', unsigned: true }),
  sampleOrderNo: varchar('sample_order_no', { length: 50 }).notNull(),
  productId: bigint('product_id', { mode: 'number', unsigned: true }),
  productName: varchar('product_name', { length: 200 }),
  customerId: bigint('customer_id', { mode: 'number', unsigned: true }),
  customerName: varchar('customer_name', { length: 100 }),
  standardCardId: bigint('standard_card_id', { mode: 'number', unsigned: true }),
  standardCardNo: varchar('standard_card_no', { length: 50 }),
  processCardId: bigint('process_card_id', { mode: 'number', unsigned: true }),
  processCardNo: varchar('process_card_no', { length: 50 }),
  status: tinyint('status').default(1),
  remark: text('remark'),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
  deleted: tinyint('deleted').default(0),
  transferNo: varchar('transfer_no', { length: 50 }),
  productCode: varchar('product_code', { length: 50 }),
  sampleParams: text('sample_params'),
  massParams: text('mass_params'),
  sopFile: varchar('sop_file', { length: 500 }),
  bomId: bigint('bom_id', { mode: 'number', unsigned: true }),
  bomVersion: varchar('bom_version', { length: 20 }),
  processRoute: varchar('process_route', { length: 500 }),
  checkStandard: text('check_standard'),
  specialNote: text('special_note'),
  sampleConfirmer: varchar('sample_confirmer', { length: 50 }),
  sampleConfirmDate: date('sample_confirm_date'),
  engConfirmer: varchar('eng_confirmer', { length: 50 }),
  engConfirmDate: date('eng_confirm_date'),
  prodConfirmer: varchar('prod_confirmer', { length: 50 }),
  prodConfirmDate: date('prod_confirm_date'),
  qualityConfirmer: varchar('quality_confirmer', { length: 50 }),
  qualityConfirmDate: date('quality_confirm_date'),
  createBy: bigint('create_by', { mode: 'number', unsigned: true }),
  workorderId: bigint('workorder_id', { mode: 'number', unsigned: true }),
  workorderNo: varchar('workorder_no', { length: 50 }),
  conversionDate: date('conversion_date'),
  approvedBy: varchar('approved_by', { length: 50 }),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
}));

export const engSop = mysqlTable('eng_sop', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  sopNo: varchar('sop_no', { length: 50 }).notNull(),
  sopName: varchar('sop_name', { length: 200 }),
  productId: bigint('product_id', { mode: 'number', unsigned: true }),
  productCode: varchar('product_code', { length: 50 }),
  productName: varchar('product_name', { length: 200 }),
  processCode: varchar('process_code', { length: 50 }),
  processName: varchar('process_name', { length: 100 }),
  version: varchar('version', { length: 10 }).default('V1.0'),
  sopType: varchar('sop_type', { length: 20 }).default('printing'),
  content: text('content'),
  fileUrl: varchar('file_url', { length: 255 }),
  workshop: varchar('workshop', { length: 100 }),
  equipmentType: varchar('equipment_type', { length: 50 }),
  effectiveDate: date('effective_date'),
  remark: text('remark'),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
  deleted: tinyint('deleted').default(0),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
}));

