import { finReceivable } from './finance';
import { invMaterial } from './warehouse';
import { invWarehouse } from './warehouse';
import { crmCustomer } from './_gen_crm';
// AUTO-GENERATED by scripts/_audit/gen_sal.cjs (2026-08-26)
// 来源: live information_schema. 建模 11 张核心 sal_* 缺失表。
// 注意：sal_delivery 因与已建模 sal_delivery_order(salDelivery) 冲突，导出名改为 salDeliveryHdr。
// 跨域 FK / 自引用 FK 以注释保留；内部 sal_* FK 实写。
import { mysqlTable, int, bigint, smallint, mediumint, tinyint, varchar, char, decimal, float, double, text, date, datetime, timestamp, time, json, mysqlEnum, primaryKey, index, uniqueIndex, foreignKey } from 'drizzle-orm/mysql-core';
import { sql } from 'drizzle-orm';
import { salOrder, salOrderDetail, salReturnOrder } from './sales';

// SKIP-FK (cross-domain): sal_delivery.customerId -> crm_customer.id [/]
// SKIP-FK (cross-domain): sal_delivery.warehouseId -> inv_warehouse.id [/]
export const salDeliveryHdr = mysqlTable('sal_delivery', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  deliveryNo: varchar('delivery_no', { length: 50 }).notNull(),
  deliveryDate: date('delivery_date'),
  orderId: bigint('order_id', { mode: 'number', unsigned: true }),
  orderNo: varchar('order_no', { length: 50 }),
  customerId: bigint('customer_id', { mode: 'number', unsigned: true }).notNull(),
  customerName: varchar('customer_name', { length: 100 }),
  warehouseId: bigint('warehouse_id', { mode: 'number', unsigned: true }).notNull(),
  totalAmount: decimal('total_amount', { precision: 18, scale: 4 }).default('0.0000'),
  totalQty: decimal('total_qty', { precision: 18, scale: 4 }).default('0.0000'),
  logisticsCompany: varchar('logistics_company', { length: 100 }),
  trackingNo: varchar('tracking_no', { length: 50 }),
  contactName: varchar('contact_name', { length: 50 }),
  contactPhone: varchar('contact_phone', { length: 30 }),
  deliveryAddress: varchar('delivery_address', { length: 500 }),
  status: tinyint('status').default(1),
  remark: text('remark'),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
  createBy: bigint('create_by', { mode: 'number', unsigned: true }),
  shipBy: bigint('ship_by', { mode: 'number', unsigned: true }),
  shipTime: datetime('ship_time'),
  signBy: bigint('sign_by', { mode: 'number', unsigned: true }),
  signTime: datetime('sign_time'),
  signStatus: tinyint('sign_status').default(0),
  deleted: tinyint('deleted').notNull().default(0),
  version: int('version').default(0),
  updateBy: bigint('update_by', { mode: 'number', unsigned: true }),
}, (t) => ({
  idxCustomer: index('idx_customer').on(t.customerId),
  idxOrder: index('idx_order').on(t.orderId),
  idxWarehouse: index('idx_warehouse').on(t.warehouseId),
  pk: primaryKey({ columns: [t.id] }),
  ukDeliveryNo: uniqueIndex('uk_delivery_no').on(t.deliveryNo),
  fkSalDeliveryOrder: foreignKey({ columns: [t.orderId], foreignColumns: [salOrder.id] }),
    fk_crmCustomer_customerId: foreignKey({
      name: 'fk_sal_delivery_customer',
      columns: [t.customerId],
      foreignColumns: [crmCustomer.id],
    })
      .onDelete('restrict')
      .onUpdate('cascade'),
    fk_invWarehouse_warehouseId: foreignKey({
      name: 'fk_sal_delivery_warehouse',
      columns: [t.warehouseId],
      foreignColumns: [invWarehouse.id],
    })
      .onDelete('restrict')
      .onUpdate('cascade'),
  }));

export const salDeliveryOrderItem = mysqlTable('sal_delivery_order_item', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  deliveryId: bigint('delivery_id', { mode: 'number', unsigned: true }).notNull(),
  orderDetailId: bigint('order_detail_id', { mode: 'number', unsigned: true }),
  materialId: bigint('material_id', { mode: 'number', unsigned: true }).notNull(),
  materialName: varchar('material_name', { length: 100 }),
  materialSpec: varchar('material_spec', { length: 255 }),
  quantity: decimal('quantity', { precision: 18, scale: 4 }).notNull(),
  unit: varchar('unit', { length: 20 }),
  unitPrice: decimal('unit_price', { precision: 18, scale: 4 }),
  amount: decimal('amount', { precision: 18, scale: 4 }),
  batchNo: varchar('batch_no', { length: 50 }),
  signQty: decimal('sign_qty', { precision: 18, scale: 4 }).default('0.0000'),
  remark: varchar('remark', { length: 255 }),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  idxDelivery: index('idx_delivery').on(t.deliveryId),
  idxMaterial: index('idx_material').on(t.materialId),
  pk: primaryKey({ columns: [t.id] }),
}));

export const salOrderItem = mysqlTable('sal_order_item', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  orderId: bigint('order_id', { mode: 'number', unsigned: true }).notNull(),
  materialId: bigint('material_id', { mode: 'number', unsigned: true }),
  materialCode: varchar('material_code', { length: 50 }),
  materialName: varchar('material_name', { length: 200 }),
  quantity: decimal('quantity', { precision: 14, scale: 3 }).default('0.000'),
  unit: varchar('unit', { length: 20 }),
  unitPrice: decimal('unit_price', { precision: 14, scale: 4 }).default('0.0000'),
  totalPrice: decimal('total_price', { precision: 14, scale: 2 }).default('0.00'),
  remark: text('remark'),
  deleted: tinyint('deleted').default(0),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  idxOrder: index('idx_order').on(t.orderId),
  pk: primaryKey({ columns: [t.id] }),
}));

export const salReconciliationDetail = mysqlTable('sal_reconciliation_detail', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  reconciliationId: bigint('reconciliation_id', { mode: 'number', unsigned: true }).notNull(),
  sourceType: tinyint('source_type').notNull(),
  sourceId: bigint('source_id', { mode: 'number', unsigned: true }),
  sourceNo: varchar('source_no', { length: 50 }),
  sourceDate: date('source_date'),
  amount: decimal('amount', { precision: 18, scale: 4 }).notNull(),
  remark: varchar('remark', { length: 255 }),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  idxReconciliation: index('idx_reconciliation').on(t.reconciliationId),
  idxSource: index('idx_source').on(t.sourceType, t.sourceId),
  pk: primaryKey({ columns: [t.id] }),
}));

export const salReconciliationLine = mysqlTable('sal_reconciliation_line', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  reconciliationId: bigint('reconciliation_id', { mode: 'number', unsigned: true }).notNull(),
  sourceType: tinyint('source_type').notNull(),
  sourceId: bigint('source_id', { mode: 'number', unsigned: true }).notNull(),
  sourceNo: varchar('source_no', { length: 50 }).notNull(),
  sourceDate: date('source_date').notNull(),
  amount: decimal('amount', { precision: 18, scale: 4 }).notNull(),
  remark: varchar('remark', { length: 255 }),
  deleted: tinyint('deleted').notNull().default(0),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  idxReconciliation: index('idx_reconciliation').on(t.reconciliationId),
  idxSource: index('idx_source').on(t.sourceType, t.sourceId),
  idxSourceNo: index('idx_source_no').on(t.sourceNo),
  pk: primaryKey({ columns: [t.id] }),
}));

export const salReconciliationWriteoff = mysqlTable('sal_reconciliation_writeoff', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  reconciliationId: bigint('reconciliation_id', { mode: 'number', unsigned: true }).notNull(),
  receivableId: bigint('receivable_id', { mode: 'number', unsigned: true }).notNull(),
  amount: decimal('amount', { precision: 18, scale: 4 }).notNull(),
  writeOffDate: date('write_off_date').notNull(),
  remark: varchar('remark', { length: 255 }),
  deleted: tinyint('deleted').notNull().default(0),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  createBy: bigint('create_by', { mode: 'number', unsigned: true }),
}, (t) => ({
  idxReceivable: index('idx_receivable').on(t.receivableId),
  idxReconciliation: index('idx_reconciliation').on(t.reconciliationId),
  idxWriteOffDate: index('idx_write_off_date').on(t.writeOffDate),
  pk: primaryKey({ columns: [t.id] }),
}));

export const salReturnOrderItem = mysqlTable('sal_return_order_item', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  returnId: bigint('return_id', { mode: 'number', unsigned: true }).notNull(),
  deliveryItemId: bigint('delivery_item_id', { mode: 'number', unsigned: true }),
  materialId: bigint('material_id', { mode: 'number', unsigned: true }).notNull(),
  materialName: varchar('material_name', { length: 100 }),
  materialSpec: varchar('material_spec', { length: 255 }),
  quantity: decimal('quantity', { precision: 18, scale: 4 }).notNull(),
  unit: varchar('unit', { length: 20 }),
  unitPrice: decimal('unit_price', { precision: 18, scale: 4 }),
  amount: decimal('amount', { precision: 18, scale: 4 }),
  batchNo: varchar('batch_no', { length: 50 }),
  inspectionQty: decimal('inspection_qty', { precision: 18, scale: 4 }).default('0.0000'),
  qualifiedQty: decimal('qualified_qty', { precision: 18, scale: 4 }).default('0.0000'),
  remark: varchar('remark', { length: 255 }),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  idxMaterial: index('idx_material').on(t.materialId),
  idxReturn: index('idx_return').on(t.returnId),
  pk: primaryKey({ columns: [t.id] }),
  fkSalReturnOrderItemReturn: foreignKey({ columns: [t.returnId], foreignColumns: [salReturnOrder.id] }),
}));

export const salSampleInventory = mysqlTable('sal_sample_inventory', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  sampleOrderId: bigint('sample_order_id', { mode: 'number', unsigned: true }),
  productName: varchar('product_name', { length: 200 }),
  materialNo: varchar('material_no', { length: 50 }),
  quantity: int('quantity').default(0),
  unit: varchar('unit', { length: 20 }).default('pcs'),
  warehouseId: bigint('warehouse_id', { mode: 'number', unsigned: true }),
  status: varchar('status', { length: 20 }).default('available'),
  sentTo: varchar('sent_to', { length: 200 }),
  sentDate: date('sent_date'),
  remark: text('remark'),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
  deleted: tinyint('deleted').default(0),
}, (t) => ({
  idxSampleOrder: index('idx_sample_order').on(t.sampleOrderId),
  pk: primaryKey({ columns: [t.id] }),
}));

// SKIP-FK (cross-domain): sal_delivery_detail.materialId -> inv_material.id [/]
export const salDeliveryDetail = mysqlTable('sal_delivery_detail', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  deliveryId: bigint('delivery_id', { mode: 'number', unsigned: true }).notNull(),
  lineNo: int('line_no'),
  materialId: bigint('material_id', { mode: 'number', unsigned: true }).notNull(),
  materialCode: varchar('material_code', { length: 50 }),
  materialName: varchar('material_name', { length: 200 }),
  materialSpec: varchar('material_spec', { length: 100 }),
  orderDetailId: bigint('order_detail_id', { mode: 'number', unsigned: true }),
  quantity: decimal('quantity', { precision: 18, scale: 4 }).notNull(),
  unit: varchar('unit', { length: 20 }),
  unitPrice: decimal('unit_price', { precision: 18, scale: 4 }),
  amount: decimal('amount', { precision: 18, scale: 4 }),
  batchNo: varchar('batch_no', { length: 50 }),
  remark: varchar('remark', { length: 255 }),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  deleted: tinyint('deleted').notNull().default(0),
}, (t) => ({
  idxDelivery: index('idx_delivery').on(t.deliveryId),
  idxMaterial: index('idx_material').on(t.materialId),
  idxOrderDetail: index('idx_order_detail').on(t.orderDetailId),
  pk: primaryKey({ columns: [t.id] }),
  fkDeliveryDetailDelivery: foreignKey({ columns: [t.deliveryId], foreignColumns: [salDeliveryHdr.id] }),
  fkSalDeliveryDetailDelivery: foreignKey({ columns: [t.deliveryId], foreignColumns: [salDeliveryHdr.id] }),
  fkSalDeliveryDetailOrderDetail: foreignKey({ columns: [t.orderDetailId], foreignColumns: [salOrderDetail.id] }),
    fk_invMaterial_materialId: foreignKey({
      name: 'fk_sal_delivery_detail_material',
      columns: [t.materialId],
      foreignColumns: [invMaterial.id],
    })
      .onDelete('restrict')
      .onUpdate('cascade'),
  }));

// SKIP-FK (cross-domain): sal_return.customerId -> crm_customer.id [/]
// SKIP-FK (cross-domain): sal_return.receivableId -> fin_receivable.id [/]
// SKIP-FK (cross-domain): sal_return.warehouseId -> inv_warehouse.id [/]
export const salReturn = mysqlTable('sal_return', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  returnNo: varchar('return_no', { length: 50 }).notNull(),
  status: tinyint('status').notNull().default(1),
  orderId: bigint('order_id', { mode: 'number', unsigned: true }).notNull(),
  orderNo: varchar('order_no', { length: 50 }),
  customerId: bigint('customer_id', { mode: 'number', unsigned: true }).notNull(),
  customerName: varchar('customer_name', { length: 100 }),
  warehouseId: bigint('warehouse_id', { mode: 'number', unsigned: true }).notNull(),
  deliveryId: bigint('delivery_id', { mode: 'number', unsigned: true }),
  deliveryNo: varchar('delivery_no', { length: 50 }),
  reason: varchar('reason', { length: 500 }).notNull(),
  returnDate: date('return_date').notNull(),
  totalAmount: decimal('total_amount', { precision: 18, scale: 4 }).default('0.0000'),
  approveBy: bigint('approve_by', { mode: 'number', unsigned: true }),
  approveTime: datetime('approve_time'),
  completeBy: bigint('complete_by', { mode: 'number', unsigned: true }),
  completeTime: datetime('complete_time'),
  inboundOrderId: bigint('inbound_order_id', { mode: 'number', unsigned: true }),
  inboundOrderNo: varchar('inbound_order_no', { length: 50 }),
  receivableId: bigint('receivable_id', { mode: 'number', unsigned: true }),
  receivableNo: varchar('receivable_no', { length: 50 }),
  remark: varchar('remark', { length: 500 }),
  version: int('version').default(0),
  deleted: tinyint('deleted').notNull().default(0),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
  createBy: bigint('create_by', { mode: 'number', unsigned: true }),
  updateBy: bigint('update_by', { mode: 'number', unsigned: true }),
}, (t) => ({
  idxCustomer: index('idx_customer').on(t.customerId),
  idxDelivery: index('idx_delivery').on(t.deliveryId),
  idxInboundOrder: index('idx_inbound_order').on(t.inboundOrderId),
  idxOrder: index('idx_order').on(t.orderId),
  idxReceivable: index('idx_receivable').on(t.receivableId),
  idxReturnDate: index('idx_return_date').on(t.returnDate),
  idxStatus: index('idx_status').on(t.status),
  idxWarehouse: index('idx_warehouse').on(t.warehouseId),
  pk: primaryKey({ columns: [t.id] }),
  ukReturnNo: uniqueIndex('uk_return_no').on(t.returnNo),
  fkSalReturnDelivery: foreignKey({ columns: [t.deliveryId], foreignColumns: [salDeliveryHdr.id] }),
  fkSalReturnOrder: foreignKey({ columns: [t.orderId], foreignColumns: [salOrder.id] }),
    fk_crmCustomer_customerId: foreignKey({
      name: 'fk_sal_return_customer',
      columns: [t.customerId],
      foreignColumns: [crmCustomer.id],
    })
      .onDelete('restrict')
      .onUpdate('cascade'),
    fk_finReceivable_receivableId: foreignKey({
      name: 'fk_sal_return_receivable',
      columns: [t.receivableId],
      foreignColumns: [finReceivable.id],
    })
      .onDelete('set null')
      .onUpdate('cascade'),
    fk_invWarehouse_warehouseId: foreignKey({
      name: 'fk_sal_return_warehouse',
      columns: [t.warehouseId],
      foreignColumns: [invWarehouse.id],
    })
      .onDelete('restrict')
      .onUpdate('cascade'),
  }));

// SKIP-FK (cross-domain): sal_return_detail.materialId -> inv_material.id [/]
export const salReturnDetail = mysqlTable('sal_return_detail', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  returnId: bigint('return_id', { mode: 'number', unsigned: true }).notNull(),
  lineNo: int('line_no').notNull(),
  deliveryDetailId: bigint('delivery_detail_id', { mode: 'number', unsigned: true }),
  orderDetailId: bigint('order_detail_id', { mode: 'number', unsigned: true }),
  materialId: bigint('material_id', { mode: 'number', unsigned: true }).notNull(),
  materialCode: varchar('material_code', { length: 50 }),
  materialName: varchar('material_name', { length: 200 }),
  materialSpec: varchar('material_spec', { length: 100 }),
  unit: varchar('unit', { length: 20 }),
  quantity: decimal('quantity', { precision: 18, scale: 4 }).notNull(),
  unitPrice: decimal('unit_price', { precision: 18, scale: 4 }).default('0.0000'),
  amount: decimal('amount', { precision: 18, scale: 4 }).default('0.0000'),
  batchNo: varchar('batch_no', { length: 50 }),
  remark: varchar('remark', { length: 255 }),
  deleted: tinyint('deleted').notNull().default(0),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  idxBatch: index('idx_batch').on(t.batchNo),
  idxDeliveryDetail: index('idx_delivery_detail').on(t.deliveryDetailId),
  idxMaterial: index('idx_material').on(t.materialId),
  idxOrderDetail: index('idx_order_detail').on(t.orderDetailId),
  idxReturn: index('idx_return').on(t.returnId),
  pk: primaryKey({ columns: [t.id] }),
  fkReturnDetailReturn: foreignKey({ columns: [t.returnId], foreignColumns: [salReturn.id] }),
  fkSalReturnDetailDeliveryDetail: foreignKey({ columns: [t.deliveryDetailId], foreignColumns: [salDeliveryDetail.id] }),
  fkSalReturnDetailOrderDetail: foreignKey({ columns: [t.orderDetailId], foreignColumns: [salOrderDetail.id] }),
    fk_invMaterial_materialId: foreignKey({
      name: 'fk_sal_return_detail_material',
      columns: [t.materialId],
      foreignColumns: [invMaterial.id],
    })
      .onDelete('restrict')
      .onUpdate('cascade'),
  }));

