// AUTO-GENERATED by scripts/_audit/gen_misc.cjs (2026-08-26)
// 域: qms ｜ 来源: live information_schema ｜ 建模 5 张核心缺失表。
// 导出名冲突自动规避（追加 Gen 后缀）；跨域 FK 注释保留；内部/已建模 FK 实写。
import { mysqlTable, int, bigint, smallint, mediumint, tinyint, varchar, char, decimal, float, double, text, date, datetime, timestamp, time, json, mysqlEnum, primaryKey, index, uniqueIndex, foreignKey } from 'drizzle-orm/mysql-core';
import { sql } from 'drizzle-orm';

export const qmsComplaint = mysqlTable('qms_complaint', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  complaintNo: varchar('complaint_no', { length: 50 }).notNull(),
  customerId: bigint('customer_id', { mode: 'number', unsigned: true }),
  customerName: varchar('customer_name', { length: 100 }),
  materialId: bigint('material_id', { mode: 'number', unsigned: true }),
  materialCode: varchar('material_code', { length: 50 }),
  materialName: varchar('material_name', { length: 200 }),
  complaintType: varchar('complaint_type', { length: 20 }),
  complaintDesc: text('complaint_desc'),
  complaintDate: date('complaint_date'),
  status: tinyint('status').default(0),
  handlerId: bigint('handler_id', { mode: 'number', unsigned: true }),
  handlerName: varchar('handler_name', { length: 50 }),
  remark: text('remark'),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  deleted: tinyint('deleted').notNull().default(0),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
}));

export const qmsLabTest = mysqlTable('qms_lab_test', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  testNo: varchar('test_no', { length: 50 }).notNull(),
  materialId: bigint('material_id', { mode: 'number', unsigned: true }),
  materialCode: varchar('material_code', { length: 50 }),
  materialName: varchar('material_name', { length: 200 }),
  testType: varchar('test_type', { length: 20 }),
  testItems: varchar('test_items', { length: 500 }),
  testMethod: varchar('test_method', { length: 200 }),
  testDate: date('test_date'),
  testResult: varchar('test_result', { length: 20 }),
  status: tinyint('status').default(1),
  testerId: bigint('tester_id', { mode: 'number', unsigned: true }),
  testerName: varchar('tester_name', { length: 50 }),
  remark: text('remark'),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  deleted: tinyint('deleted').notNull().default(0),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
}));

export const qmsSgsCert = mysqlTable('qms_sgs_cert', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  certNo: varchar('cert_no', { length: 50 }).notNull(),
  materialId: bigint('material_id', { mode: 'number', unsigned: true }),
  materialCode: varchar('material_code', { length: 50 }),
  materialName: varchar('material_name', { length: 200 }),
  supplierId: bigint('supplier_id', { mode: 'number', unsigned: true }),
  supplierName: varchar('supplier_name', { length: 200 }),
  certType: varchar('cert_type', { length: 20 }),
  testItems: varchar('test_items', { length: 500 }),
  testResult: varchar('test_result', { length: 20 }),
  testReportNo: varchar('test_report_no', { length: 50 }),
  testOrg: varchar('test_org', { length: 100 }),
  issueDate: date('issue_date'),
  expireDate: date('expire_date'),
  status: tinyint('status').default(1),
  fileUrl: varchar('file_url', { length: 500 }),
  remark: text('remark'),
  deleted: tinyint('deleted').default(0),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
}));

export const qmsSgsCertItem = mysqlTable('qms_sgs_cert_item', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  certId: bigint('cert_id', { mode: 'number', unsigned: true }).notNull(),
  itemName: varchar('item_name', { length: 100 }).notNull(),
  limitValue: varchar('limit_value', { length: 50 }),
  testValue: varchar('test_value', { length: 50 }),
  result: varchar('result', { length: 20 }),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  deleted: tinyint('deleted').notNull().default(0),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
}));

export const qmsSupplierAudit = mysqlTable('qms_supplier_audit', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  auditNo: varchar('audit_no', { length: 50 }).notNull(),
  supplierId: bigint('supplier_id', { mode: 'number', unsigned: true }),
  supplierCode: varchar('supplier_code', { length: 50 }),
  supplierName: varchar('supplier_name', { length: 200 }),
  auditType: varchar('audit_type', { length: 20 }),
  auditDate: date('audit_date'),
  auditResult: varchar('audit_result', { length: 20 }),
  status: tinyint('status').default(1),
  auditorId: bigint('auditor_id', { mode: 'number', unsigned: true }),
  auditorName: varchar('auditor_name', { length: 50 }),
  remark: text('remark'),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  deleted: tinyint('deleted').notNull().default(0),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
}));

