// AUTO-GENERATED by scripts/_audit/gen_misc.cjs (2026-08-26)
// 域: srm ｜ 来源: live information_schema ｜ 建模 2 张核心缺失表。
// 导出名冲突自动规避（追加 Gen 后缀）；跨域 FK 注释保留；内部/已建模 FK 实写。
import { mysqlTable, int, bigint, smallint, mediumint, tinyint, varchar, char, decimal, float, double, text, date, datetime, timestamp, time, json, mysqlEnum, primaryKey, index, uniqueIndex, foreignKey } from 'drizzle-orm/mysql-core';
import { sql } from 'drizzle-orm';

export const srmSupplierEval = mysqlTable('srm_supplier_eval', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  evalNo: varchar('eval_no', { length: 50 }).notNull(),
  supplierId: bigint('supplier_id', { mode: 'number', unsigned: true }),
  supplierName: varchar('supplier_name', { length: 200 }).default(''),
  evalPeriod: varchar('eval_period', { length: 20 }).default('month'),
  periodStart: date('period_start'),
  periodEnd: date('period_end'),
  qualityScore: decimal('quality_score', { precision: 5, scale: 2 }).default('0.00'),
  deliveryScore: decimal('delivery_score', { precision: 5, scale: 2 }).default('0.00'),
  priceScore: decimal('price_score', { precision: 5, scale: 2 }).default('0.00'),
  serviceScore: decimal('service_score', { precision: 5, scale: 2 }).default('0.00'),
  totalScore: decimal('total_score', { precision: 5, scale: 2 }).default('0.00'),
  qualityRate: decimal('quality_rate', { precision: 5, scale: 2 }).default('0.00'),
  onTimeRate: decimal('on_time_rate', { precision: 5, scale: 2 }).default('0.00'),
  orderCount: int('order_count').default(0),
  defectCount: int('defect_count').default(0),
  supplierLevel: varchar('supplier_level', { length: 5 }).default('C'),
  status: tinyint('status').default(0),
  evaluator: varchar('evaluator', { length: 100 }).default(''),
  evalTime: datetime('eval_time'),
  remark: text('remark'),
  deleted: tinyint('deleted').default(0),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
  ukEvalNo: uniqueIndex('uk_eval_no').on(t.evalNo),
}));

export const srmSupplierEvalItem = mysqlTable('srm_supplier_eval_item', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  evalId: bigint('eval_id', { mode: 'number', unsigned: true }).notNull(),
  category: varchar('category', { length: 50 }).default(''),
  itemName: varchar('item_name', { length: 200 }).default(''),
  weight: decimal('weight', { precision: 5, scale: 2 }).default('0.00'),
  score: decimal('score', { precision: 5, scale: 2 }).default('0.00'),
  actualValue: varchar('actual_value', { length: 100 }).default(''),
  targetValue: varchar('target_value', { length: 100 }).default(''),
  remark: text('remark'),
  sortOrder: int('sort_order').default(0),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
}));

