// AUTO-GENERATED by scripts/_audit/gen_misc.cjs (2026-08-26)
// 域: hr ｜ 来源: live information_schema ｜ 建模 3 张核心缺失表。
// 2026-09-18 P2 治理：已移除 hr_certificates / hr_schedules / hr_shifts 三张遗留表模型
// （代码实际使用单数表 hr_certificate / hr_schedule / hr_shift）。
// 导出名冲突自动规避（追加 Gen 后缀）；跨域 FK 注释保留；内部/已建模 FK 实写。
import { mysqlTable, bigint, tinyint, varchar, text, datetime, primaryKey } from 'drizzle-orm/mysql-core';
import { sql } from 'drizzle-orm';

export const hrMesSync = mysqlTable('hr_mes_sync', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  employeeId: bigint('employee_id', { mode: 'number', unsigned: true }).notNull(),
  employeeName: varchar('employee_name', { length: 50 }),
  syncType: varchar('sync_type', { length: 20 }),
  syncData: text('sync_data'),
  syncStatus: tinyint('sync_status').default(1),
  lastSyncTime: datetime('last_sync_time'),
  remark: varchar('remark', { length: 255 }),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
}));

export const hrOrganization = mysqlTable('hr_organization', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  orgCode: varchar('org_code', { length: 50 }).notNull(),
  orgName: varchar('org_name', { length: 100 }).notNull(),
  parentId: bigint('parent_id', { mode: 'number', unsigned: true }).default(0),
  orgType: varchar('org_type', { length: 20 }),
  status: tinyint('status').default(1),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
}));

export const hrSkills = mysqlTable('hr_skills', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  skillCode: varchar('skill_code', { length: 50 }).notNull(),
  skillName: varchar('skill_name', { length: 100 }).notNull(),
  skillType: varchar('skill_type', { length: 20 }),
  description: varchar('description', { length: 255 }),
  status: tinyint('status').default(1),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
}));

