// AUTO-GENERATED by scripts/_audit/gen_misc.cjs (2026-08-26)
// 域: crm ｜ 来源: live information_schema ｜ 建模 5 张核心缺失表。
// 导出名冲突自动规避（追加 Gen 后缀）；跨域 FK 注释保留；内部/已建模 FK 实写。
import { mysqlTable, int, bigint, smallint, mediumint, tinyint, varchar, char, decimal, float, double, text, date, datetime, timestamp, time, json, mysqlEnum, primaryKey, index, uniqueIndex, foreignKey } from 'drizzle-orm/mysql-core';
import { sql } from 'drizzle-orm';
import { sysUser } from './system';

export const crmCustomer = mysqlTable('crm_customer', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  customerCode: varchar('customer_code', { length: 50 }).notNull(),
  customerName: varchar('customer_name', { length: 100 }).notNull(),
  shortName: varchar('short_name', { length: 50 }),
  customerType: tinyint('customer_type'),
  industry: varchar('industry', { length: 50 }),
  scale: varchar('scale', { length: 50 }),
  creditLevel: varchar('credit_level', { length: 20 }),
  province: varchar('province', { length: 50 }),
  city: varchar('city', { length: 50 }),
  district: varchar('district', { length: 50 }),
  address: varchar('address', { length: 255 }),
  contactName: varchar('contact_name', { length: 50 }),
  contactPhone: varchar('contact_phone', { length: 20 }),
  contactEmail: varchar('contact_email', { length: 100 }),
  fax: varchar('fax', { length: 20 }),
  website: varchar('website', { length: 100 }),
  businessLicense: varchar('business_license', { length: 50 }),
  taxNumber: varchar('tax_number', { length: 50 }),
  bankName: varchar('bank_name', { length: 100 }),
  bankAccount: varchar('bank_account', { length: 50 }),
  salesmanId: bigint('salesman_id', { mode: 'number', unsigned: true }),
  followUpStatus: tinyint('follow_up_status').default(1),
  status: tinyint('status').default(1),
  remark: text('remark'),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
  createBy: bigint('create_by', { mode: 'number', unsigned: true }),
  updateBy: bigint('update_by', { mode: 'number', unsigned: true }),
  deleted: tinyint('deleted').notNull().default(0),
}, (t) => ({
  idxCustomerCode: index('idx_customer_code').on(t.customerCode),
  idxCustomerStatus: index('idx_customer_status').on(t.status, t.deleted),
  pk: primaryKey({ columns: [t.id] }),
  ukCustomerCode: uniqueIndex('uk_customer_code').on(t.customerCode),
  fkCrmCustomerSalesman: foreignKey({ columns: [t.salesmanId], foreignColumns: [sysUser.id] }),
}));

export const crmCustomerAnalysis = mysqlTable('crm_customer_analysis', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  customerId: bigint('customer_id', { mode: 'number', unsigned: true }).notNull(),
  customerName: varchar('customer_name', { length: 100 }).default(''),
  analysisPeriod: varchar('analysis_period', { length: 20 }).default('month'),
  periodStart: date('period_start'),
  periodEnd: date('period_end'),
  orderCount: int('order_count').default(0),
  orderAmount: decimal('order_amount', { precision: 12, scale: 2 }).default('0.00'),
  deliveryCount: int('delivery_count').default(0),
  returnCount: int('return_count').default(0),
  complaintCount: int('complaint_count').default(0),
  onTimeRate: decimal('on_time_rate', { precision: 5, scale: 2 }),
  satisfactionScore: decimal('satisfaction_score', { precision: 3, scale: 1 }),
  customerLevel: varchar('customer_level', { length: 5 }).default('C'),
  growthRate: decimal('growth_rate', { precision: 5, scale: 2 }),
  remark: text('remark'),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  idxCustomer: index('idx_customer').on(t.customerId),
  idxLevel: index('idx_level').on(t.customerLevel),
  idxPeriod: index('idx_period').on(t.analysisPeriod),
  pk: primaryKey({ columns: [t.id] }),
}));

export const crmCustomerFollowUp = mysqlTable('crm_customer_follow_up', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  customerId: bigint('customer_id', { mode: 'number', unsigned: true }).notNull(),
  followUpType: tinyint('follow_up_type'),
  followUpContent: text('follow_up_content'),
  followUpTime: datetime('follow_up_time'),
  nextFollowUpTime: datetime('next_follow_up_time'),
  followUpBy: bigint('follow_up_by', { mode: 'number', unsigned: true }),
  attachment: varchar('attachment', { length: 255 }),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  deleted: tinyint('deleted').notNull().default(0),
}, (t) => ({
  idxCustomer: index('idx_customer').on(t.customerId),
  idxFollowUpTime: index('idx_follow_up_time').on(t.followUpTime),
  pk: primaryKey({ columns: [t.id] }),
}));

export const crmFollowRecord = mysqlTable('crm_follow_record', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  customerId: bigint('customer_id', { mode: 'number', unsigned: true }).notNull(),
  customerName: varchar('customer_name', { length: 100 }).default(''),
  followType: varchar('follow_type', { length: 20 }).default('phone'),
  followContent: text('follow_content'),
  contactName: varchar('contact_name', { length: 100 }),
  salesmanName: varchar('salesman_name', { length: 100 }),
  nextFollowDate: date('next_follow_date'),
  opportunity: varchar('opportunity', { length: 200 }),
  status: tinyint('status').default(1),
  remark: text('remark'),
  deleted: tinyint('deleted').default(0),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  idxCreateTime: index('idx_create_time').on(t.createTime),
  idxCustomer: index('idx_customer').on(t.customerId),
  idxFollowType: index('idx_follow_type').on(t.followType),
  pk: primaryKey({ columns: [t.id] }),
}));

export const crmCustomerContact = mysqlTable('crm_customer_contact', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  customerId: bigint('customer_id', { mode: 'number', unsigned: true }).notNull(),
  contactName: varchar('contact_name', { length: 50 }).notNull(),
  position: varchar('position', { length: 50 }),
  phone: varchar('phone', { length: 20 }),
  email: varchar('email', { length: 100 }),
  isPrimary: tinyint('is_primary').default(0),
  remark: text('remark'),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
  deleted: tinyint('deleted').notNull().default(0),
  createBy: bigint('create_by', { mode: 'number', unsigned: true }),
  updateBy: bigint('update_by', { mode: 'number', unsigned: true }),
}, (t) => ({
  idxCustomer: index('idx_customer').on(t.customerId),
  pk: primaryKey({ columns: [t.id] }),
  fkCustomerContactCustomer: foreignKey({ columns: [t.customerId], foreignColumns: [crmCustomer.id] }),
}));

