// AUTO-GENERATED by scripts/_audit/gen_misc.cjs (2026-08-26)
// 域: bom ｜ 来源: live information_schema ｜ 建模 2 张核心缺失表。
// 导出名冲突自动规避（追加 Gen 后缀）；跨域 FK 注释保留；内部/已建模 FK 实写。
import { bigint, datetime, decimal, foreignKey, index, int, mysqlTable, primaryKey, tinyint, uniqueIndex, varchar } from 'drizzle-orm/mysql-core';
import { sql } from 'drizzle-orm';

export const bomHeader = mysqlTable('bom_header', {
  id: int('id').autoincrement().notNull(),
  bomNo: varchar('bom_no', { length: 50 }).notNull(),
  productId: int('product_id'),
  productCode: varchar('product_code', { length: 50 }),
  productName: varchar('product_name', { length: 200 }),
  productSpec: varchar('product_spec', { length: 200 }),
  version: varchar('version', { length: 20 }).default('1.0'),
  isDefault: tinyint('is_default').default(1),
  status: int('status').default(10),
  unit: varchar('unit', { length: 20 }),
  baseQty: decimal('base_qty', { precision: 12, scale: 2 }).default('1.00'),
  totalMaterialCount: int('total_material_count').default(0),
  totalCost: decimal('total_cost', { precision: 12, scale: 2 }).default('0.00'),
  remark: varchar('remark', { length: 500 }),
  deleted: tinyint('deleted').default(0),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
    createBy: varchar('create_by', { length: 100 }), // create_by
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
  ukBomNo: uniqueIndex('uk_bom_no').on(t.bomNo),
}));

export const bomLine = mysqlTable('bom_line', {
  id: int('id').autoincrement().notNull(),
  bomId: int('bom_id').notNull(),
  lineNo: int('line_no').notNull(),
  materialId: int('material_id'),
  materialCode: varchar('material_code', { length: 50 }),
  materialName: varchar('material_name', { length: 200 }),
  materialSpec: varchar('material_spec', { length: 200 }),
  materialUnit: varchar('material_unit', { length: 20 }),
  usageQty: decimal('usage_qty', { precision: 12, scale: 4 }).notNull().default('0.0000'),
  lossRate: decimal('loss_rate', { precision: 5, scale: 2 }).default('0.00'),
  unitCost: decimal('unit_cost', { precision: 12, scale: 2 }).default('0.00'),
  totalCost: decimal('total_cost', { precision: 12, scale: 2 }).default('0.00'),
  remark: varchar('remark', { length: 500 }),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
    actualQty: decimal('actual_qty', { precision: 18, scale: 4 }).default('0.0000'), // actual_qty
    consumptionQty: decimal('consumption_qty', { precision: 18, scale: 4 }).default('0.0000'), // consumption_qty
    isKeyMaterial: varchar('is_key_material', { length: 100 }), // is_key_material
    level: tinyint('level'), // level
    materialType: tinyint('material_type'), // material_type
    parentLineId: bigint('parent_line_id', { mode: 'number', unsigned: true }), // parent_line_id
    positionNo: varchar('position_no', { length: 50 }), // position_no
    processName: varchar('process_name', { length: 50 }), // process_name
    processSeq: varchar('process_seq', { length: 50 }), // process_seq
    unit: varchar('unit', { length: 100 }), // unit
}, (t) => ({
  idxBomId: index('idx_bom_id').on(t.bomId),
  pk: primaryKey({ columns: [t.id] }),
    fk_bomHeader_bomId: foreignKey({
      name: 'fk_bom_line_header',
      columns: [t.bomId],
      foreignColumns: [bomHeader.id],
    })
      .onDelete('cascade')
      .onUpdate('no action'),
  }));

