// AUTO-GENERATED by scripts/_audit/gen_misc.cjs (2026-08-26)
// 域: prd ｜ 来源: live information_schema ｜ 建模 4 张核心缺失表。
// 导出名冲突自动规避（追加 Gen 后缀）；跨域 FK 注释保留；内部/已建模 FK 实写。
import { mysqlTable, int, bigint, smallint, mediumint, tinyint, varchar, char, decimal, float, double, text, date, datetime, timestamp, time, json, mysqlEnum, primaryKey, index, uniqueIndex, foreignKey } from 'drizzle-orm/mysql-core';
import { sql } from 'drizzle-orm';

export const prdPickOrderGen2 = mysqlTable('prd_pick_order', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  pickNo: varchar('pick_no', { length: 50 }).notNull(),
  workOrderId: bigint('work_order_id', { mode: 'number', unsigned: true }).notNull(),
  warehouseId: bigint('warehouse_id', { mode: 'number', unsigned: true }),
  pickerName: varchar('picker_name', { length: 100 }),
  totalQty: decimal('total_qty', { precision: 18, scale: 4 }).default('0.0000'),
  status: tinyint('status').default(1),
  remark: text('remark'),
  createBy: bigint('create_by', { mode: 'number', unsigned: true }),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
  deleted: tinyint('deleted').default(0),
}, (t) => ({
  idxStatus: index('idx_status').on(t.status),
  idxWarehouse: index('idx_warehouse').on(t.warehouseId),
  idxWorkOrder: index('idx_work_order').on(t.workOrderId),
  pk: primaryKey({ columns: [t.id] }),
  ukPickNo: uniqueIndex('uk_pick_no').on(t.pickNo),
}));

export const prdPickOrderItemGen2 = mysqlTable('prd_pick_order_item', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  pickOrderId: bigint('pick_order_id', { mode: 'number', unsigned: true }).notNull(),
  materialId: bigint('material_id', { mode: 'number', unsigned: true }),
  materialName: varchar('material_name', { length: 200 }),
  materialSpec: varchar('material_spec', { length: 200 }),
  requiredQty: decimal('required_qty', { precision: 18, scale: 4 }).default('0.0000'),
  actualQty: decimal('actual_qty', { precision: 18, scale: 4 }).default('0.0000'),
  batchNo: varchar('batch_no', { length: 50 }),
  unitCost: decimal('unit_cost', { precision: 18, scale: 4 }).default('0.0000'),
  lineAmount: decimal('line_amount', { precision: 18, scale: 4 }).default('0.0000'),
  unit: varchar('unit', { length: 20 }).default('pcs'),
  remark: text('remark'),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  idxMaterial: index('idx_material').on(t.materialId),
  idxPickOrder: index('idx_pick_order').on(t.pickOrderId),
  pk: primaryKey({ columns: [t.id] }),
}));

export const prdReturnOrderGen2 = mysqlTable('prd_return_order', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  returnNo: varchar('return_no', { length: 50 }).notNull(),
  workOrderId: bigint('work_order_id', { mode: 'number', unsigned: true }).notNull(),
  pickOrderId: bigint('pick_order_id', { mode: 'number', unsigned: true }),
  warehouseId: bigint('warehouse_id', { mode: 'number', unsigned: true }),
  returnReason: varchar('return_reason', { length: 500 }),
  totalQty: decimal('total_qty', { precision: 18, scale: 4 }).default('0.0000'),
  status: tinyint('status').default(1),
  createBy: bigint('create_by', { mode: 'number', unsigned: true }),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
  deleted: tinyint('deleted').default(0),
}, (t) => ({
  idxPickOrder: index('idx_pick_order').on(t.pickOrderId),
  idxStatus: index('idx_status').on(t.status),
  idxWorkOrder: index('idx_work_order').on(t.workOrderId),
  pk: primaryKey({ columns: [t.id] }),
  ukReturnNo: uniqueIndex('uk_return_no').on(t.returnNo),
}));

export const prdReturnOrderItemGen2 = mysqlTable('prd_return_order_item', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  returnOrderId: bigint('return_order_id', { mode: 'number', unsigned: true }).notNull(),
  pickOrderItemId: bigint('pick_order_item_id', { mode: 'number', unsigned: true }),
  materialId: bigint('material_id', { mode: 'number', unsigned: true }),
  materialName: varchar('material_name', { length: 200 }),
  quantity: decimal('quantity', { precision: 18, scale: 4 }).default('0.0000'),
  batchNo: varchar('batch_no', { length: 50 }),
  unitCost: decimal('unit_cost', { precision: 18, scale: 4 }).default('0.0000'),
  lineAmount: decimal('line_amount', { precision: 18, scale: 4 }).default('0.0000'),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  idxMaterial: index('idx_material').on(t.materialId),
  idxReturnOrder: index('idx_return_order').on(t.returnOrderId),
  pk: primaryKey({ columns: [t.id] }),
}));

