// AUTO-GENERATED by scripts/_audit/gen_misc.cjs (2026-08-26)
// 域: domain ｜ 来源: live information_schema ｜ 建模 1 张核心缺失表。
// 导出名冲突自动规避（追加 Gen 后缀）；跨域 FK 注释保留；内部/已建模 FK 实写。
import { mysqlTable, int, bigint, smallint, mediumint, tinyint, varchar, char, decimal, float, double, text, date, datetime, timestamp, time, json, mysqlEnum, primaryKey, index, uniqueIndex, foreignKey } from 'drizzle-orm/mysql-core';
import { sql } from 'drizzle-orm';

export const domainEventOutbox = mysqlTable('domain_event_outbox', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  eventType: varchar('event_type', { length: 100 }).notNull(),
  aggregateType: varchar('aggregate_type', { length: 50 }),
  aggregateId: bigint('aggregate_id', { mode: 'number', unsigned: true }),
  payload: json('payload').notNull(),
  status: varchar('status', { length: 20 }).notNull().default('pending'),
  retryCount: int('retry_count').notNull().default(0),
  errorMessage: text('error_message'),
  nextExecuteAt: datetime('next_execute_at'),
  createTime: datetime('create_time').notNull().default(sql`CURRENT_TIMESTAMP`),
  processedAt: datetime('processed_at'),
  claimedAt: datetime('claimed_at'),
  dispatchedAt: datetime('dispatched_at'),
}, (t) => ({
  idxAggregate: index('idx_aggregate').on(t.aggregateType, t.aggregateId),
  idxStatusCreated: index('idx_status_created').on(t.status, t.createTime),
  idxStatusNextExecute: index('idx_status_next_execute').on(t.status, t.nextExecuteAt),
  pk: primaryKey({ columns: [t.id] }),
}));

