// AUTO-GENERATED by scripts/_audit/gen_misc.cjs (2026-08-26)
// 域: hr ｜ 来源: live information_schema ｜ 建模 6 张核心缺失表。
// 导出名冲突自动规避（追加 Gen 后缀）；跨域 FK 注释保留；内部/已建模 FK 实写。
import { mysqlTable, int, bigint, smallint, mediumint, tinyint, varchar, char, decimal, float, double, text, date, datetime, timestamp, time, json, mysqlEnum, primaryKey, index, uniqueIndex, foreignKey } from 'drizzle-orm/mysql-core';
import { sql } from 'drizzle-orm';

export const hrCertificates = mysqlTable('hr_certificates', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  employeeId: bigint('employee_id', { mode: 'number', unsigned: true }).notNull(),
  employeeName: varchar('employee_name', { length: 50 }),
  certName: varchar('cert_name', { length: 100 }).notNull(),
  certNo: varchar('cert_no', { length: 50 }),
  issueDate: date('issue_date'),
  expireDate: date('expire_date'),
  status: tinyint('status').default(1),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
}));

export const hrMesSync = mysqlTable('hr_mes_sync', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  employeeId: bigint('employee_id', { mode: 'number', unsigned: true }).notNull(),
  employeeName: varchar('employee_name', { length: 50 }),
  syncType: varchar('sync_type', { length: 20 }),
  syncData: text('sync_data'),
  syncStatus: tinyint('sync_status').default(1),
  lastSyncTime: datetime('last_sync_time'),
  remark: varchar('remark', { length: 255 }),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
}));

export const hrOrganization = mysqlTable('hr_organization', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  orgCode: varchar('org_code', { length: 50 }).notNull(),
  orgName: varchar('org_name', { length: 100 }).notNull(),
  parentId: bigint('parent_id', { mode: 'number', unsigned: true }).default(0),
  orgType: varchar('org_type', { length: 20 }),
  status: tinyint('status').default(1),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
}));

export const hrSchedules = mysqlTable('hr_schedules', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  scheduleDate: date('schedule_date').notNull(),
  employeeId: bigint('employee_id', { mode: 'number', unsigned: true }).notNull(),
  employeeName: varchar('employee_name', { length: 50 }),
  shiftId: bigint('shift_id', { mode: 'number', unsigned: true }).notNull(),
  shiftCode: varchar('shift_code', { length: 20 }),
  shiftName: varchar('shift_name', { length: 50 }),
  status: tinyint('status').default(1),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
}));

export const hrShifts = mysqlTable('hr_shifts', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  shiftCode: varchar('shift_code', { length: 20 }).notNull(),
  shiftName: varchar('shift_name', { length: 50 }).notNull(),
  startTime: time('start_time').notNull(),
  endTime: time('end_time').notNull(),
  duration: decimal('duration', { precision: 4, scale: 1 }),
  status: tinyint('status').default(1),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
}));

export const hrSkills = mysqlTable('hr_skills', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  skillCode: varchar('skill_code', { length: 50 }).notNull(),
  skillName: varchar('skill_name', { length: 100 }).notNull(),
  skillType: varchar('skill_type', { length: 20 }),
  description: varchar('description', { length: 255 }),
  status: tinyint('status').default(1),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
}));

