// AUTO-GENERATED by scripts/_audit/gen_misc.cjs (2026-08-26)
// 域: plm ｜ 来源: live information_schema ｜ 建模 3 张核心缺失表。
// 导出名冲突自动规避（追加 Gen 后缀）；跨域 FK 注释保留；内部/已建模 FK 实写。
import { mysqlTable, int, bigint, smallint, mediumint, tinyint, varchar, char, decimal, float, double, text, date, datetime, timestamp, time, json, mysqlEnum, primaryKey, index, uniqueIndex, foreignKey } from 'drizzle-orm/mysql-core';
import { sql } from 'drizzle-orm';

export const plmEco = mysqlTable('plm_eco', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  ecoNo: varchar('eco_no', { length: 50 }).notNull(),
  ecoTitle: varchar('eco_title', { length: 200 }).notNull(),
  productId: bigint('product_id', { mode: 'number', unsigned: true }),
  productCode: varchar('product_code', { length: 50 }),
  changeType: varchar('change_type', { length: 20 }),
  description: text('description'),
  status: tinyint('status').default(0),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
}));

export const plmLifecycle = mysqlTable('plm_lifecycle', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  productId: bigint('product_id', { mode: 'number', unsigned: true }),
  productCode: varchar('product_code', { length: 50 }),
  lifecyclePhase: varchar('lifecycle_phase', { length: 20 }),
  phaseDescription: varchar('phase_description', { length: 255 }),
  effectiveDate: date('effective_date'),
  status: tinyint('status').default(1),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
}));

export const plmProductLifecycle = mysqlTable('plm_product_lifecycle', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  productId: bigint('product_id', { mode: 'number', unsigned: true }).notNull(),
  productCode: varchar('product_code', { length: 50 }),
  productName: varchar('product_name', { length: 200 }),
  lifecycleStage: varchar('lifecycle_stage', { length: 20 }),
  stageStatus: tinyint('stage_status').default(1),
  version: varchar('version', { length: 10 }).default('V1.0'),
  changeType: varchar('change_type', { length: 20 }),
  changeReason: varchar('change_reason', { length: 255 }),
  changeDesc: text('change_desc'),
  effectiveDate: date('effective_date'),
  remark: text('remark'),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  deleted: tinyint('deleted').default(0),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
}));

