// AUTO-GENERATED by scripts/_audit/gen_misc.cjs (2026-08-26)
// 域: eqp ｜ 来源: live information_schema ｜ 建模 6 张核心缺失表。
// 导出名冲突自动规避（追加 Gen 后缀）；跨域 FK 注释保留；内部/已建模 FK 实写。
import { mysqlTable, int, bigint, smallint, mediumint, tinyint, varchar, char, decimal, float, double, text, date, datetime, timestamp, time, json, mysqlEnum, primaryKey, index, uniqueIndex, foreignKey } from 'drizzle-orm/mysql-core';
import { sql } from 'drizzle-orm';

export const eqpCalibration = mysqlTable('eqp_calibration', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  calibrationNo: varchar('calibration_no', { length: 50 }).notNull(),
  equipmentId: bigint('equipment_id', { mode: 'number', unsigned: true }),
  equipmentCode: varchar('equipment_code', { length: 50 }).default(''),
  equipmentName: varchar('equipment_name', { length: 200 }).default(''),
  calibrationDate: date('calibration_date'),
  nextCalibrationDate: date('next_calibration_date'),
  calibrationOrg: varchar('calibration_org', { length: 200 }).default(''),
  calibrationResult: varchar('calibration_result', { length: 20 }).default('qualified'),
  certificateNo: varchar('certificate_no', { length: 50 }).default(''),
  calibrationCost: decimal('calibration_cost', { precision: 12, scale: 2 }).default('0.00'),
  remark: text('remark'),
  deleted: tinyint('deleted').default(0),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
  ukCalibrationNo: uniqueIndex('uk_calibration_no').on(t.calibrationNo),
}));

export const eqpEquipment = mysqlTable('eqp_equipment', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  equipmentCode: varchar('equipment_code', { length: 50 }).notNull(),
  equipmentName: varchar('equipment_name', { length: 100 }).notNull(),
  equipmentType: tinyint('equipment_type'),
  brand: varchar('brand', { length: 50 }),
  model: varchar('model', { length: 50 }),
  serialNo: varchar('serial_no', { length: 50 }),
  workshopId: bigint('workshop_id', { mode: 'number', unsigned: true }),
  location: varchar('location', { length: 100 }),
  purchaseDate: date('purchase_date'),
  manufacturer: varchar('manufacturer', { length: 100 }),
  supplierId: bigint('supplier_id', { mode: 'number', unsigned: true }),
  warrantyExpire: date('warranty_expire'),
  ratedCapacity: decimal('rated_capacity', { precision: 18, scale: 4 }),
  currentStatus: tinyint('current_status').default(1),
  oee: decimal('oee', { precision: 5, scale: 2 }).default('0.00'),
  availability: decimal('availability', { precision: 5, scale: 2 }).default('0.00'),
  performance: decimal('performance', { precision: 5, scale: 2 }).default('0.00'),
  qualityRate: decimal('quality_rate', { precision: 5, scale: 2 }).default('0.00'),
  totalRunHours: decimal('total_run_hours', { precision: 10, scale: 2 }).default('0.00'),
  lastMaintenanceDate: date('last_maintenance_date'),
  nextMaintenanceDate: date('next_maintenance_date'),
  status: tinyint('status').default(1),
  remark: text('remark'),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
  createBy: bigint('create_by', { mode: 'number', unsigned: true }),
  deleted: tinyint('deleted').notNull().default(0),
}, (t) => ({
  idxStatus: index('idx_status').on(t.status),
  idxType: index('idx_type').on(t.equipmentType),
  pk: primaryKey({ columns: [t.id] }),
  ukEquipmentCode: uniqueIndex('uk_equipment_code').on(t.equipmentCode),
}));

export const eqpMaintenancePlan = mysqlTable('eqp_maintenance_plan', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  planNo: varchar('plan_no', { length: 50 }).notNull(),
  equipmentId: bigint('equipment_id', { mode: 'number', unsigned: true }).notNull(),
  maintenanceType: tinyint('maintenance_type'),
  cycleType: tinyint('cycle_type'),
  cycleValue: int('cycle_value'),
  planDate: date('plan_date'),
  responsibleId: bigint('responsible_id', { mode: 'number', unsigned: true }),
  content: text('content'),
  status: tinyint('status').default(1),
  completeDate: date('complete_date'),
  remark: text('remark'),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
  deleted: tinyint('deleted').default(0),
}, (t) => ({
  idxEquipment: index('idx_equipment').on(t.equipmentId),
  idxStatus: index('idx_status').on(t.status),
  pk: primaryKey({ columns: [t.id] }),
  ukPlanNo: uniqueIndex('uk_plan_no').on(t.planNo),
}));

export const eqpMaintenanceRecord = mysqlTable('eqp_maintenance_record', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  recordNo: varchar('record_no', { length: 50 }).notNull(),
  planId: bigint('plan_id', { mode: 'number', unsigned: true }),
  equipmentId: bigint('equipment_id', { mode: 'number', unsigned: true }).notNull(),
  maintenanceType: tinyint('maintenance_type'),
  faultDesc: text('fault_desc'),
  maintenanceContent: text('maintenance_content'),
  startTime: datetime('start_time'),
  endTime: datetime('end_time'),
  downtimeHours: decimal('downtime_hours', { precision: 10, scale: 2 }).default('0.00'),
  cost: decimal('cost', { precision: 18, scale: 4 }).default('0.0000'),
  responsibleId: bigint('responsible_id', { mode: 'number', unsigned: true }),
  result: tinyint('result'),
  remark: text('remark'),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
  deleted: tinyint('deleted').default(0),
}, (t) => ({
  idxEquipment: index('idx_equipment').on(t.equipmentId),
  idxPlan: index('idx_plan').on(t.planId),
  pk: primaryKey({ columns: [t.id] }),
  ukRecordNo: uniqueIndex('uk_record_no').on(t.recordNo),
}));

export const eqpRepair = mysqlTable('eqp_repair', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  repairNo: varchar('repair_no', { length: 50 }).notNull(),
  equipmentId: bigint('equipment_id', { mode: 'number', unsigned: true }),
  equipmentCode: varchar('equipment_code', { length: 50 }).default(''),
  equipmentName: varchar('equipment_name', { length: 200 }).default(''),
  faultDate: date('fault_date'),
  faultDesc: text('fault_desc'),
  repairType: varchar('repair_type', { length: 20 }).default('corrective'),
  repairPerson: varchar('repair_person', { length: 100 }).default(''),
  remark: text('remark'),
  deleted: tinyint('deleted').default(0),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
  ukRepairNo: uniqueIndex('uk_repair_no').on(t.repairNo),
}));

export const eqpScrap = mysqlTable('eqp_scrap', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  scrapNo: varchar('scrap_no', { length: 50 }).notNull(),
  equipmentId: bigint('equipment_id', { mode: 'number', unsigned: true }),
  equipmentCode: varchar('equipment_code', { length: 50 }).default(''),
  equipmentName: varchar('equipment_name', { length: 200 }).default(''),
  scrapDate: date('scrap_date'),
  scrapReason: text('scrap_reason'),
  originalValue: decimal('original_value', { precision: 12, scale: 2 }).default('0.00'),
  netValue: decimal('net_value', { precision: 12, scale: 2 }).default('0.00'),
  approvalPerson: varchar('approval_person', { length: 100 }).default(''),
  remark: text('remark'),
  deleted: tinyint('deleted').default(0),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
  ukScrapNo: uniqueIndex('uk_scrap_no').on(t.scrapNo),
}));

