// AUTO-GENERATED by scripts/_audit/gen_misc.cjs (2026-08-26)
// 域: eqp ｜ 来源: live information_schema ｜ 建模 6 张核心缺失表。
// 导出名冲突自动规避（追加 Gen 后缀）；跨域 FK 注释保留；内部/已建模 FK 实写。
import { bigint, date, datetime, decimal, index, int, json, mysqlTable, primaryKey, text, tinyint, uniqueIndex, varchar } from 'drizzle-orm/mysql-core';
import { sql } from 'drizzle-orm';

export const eqpCalibration = mysqlTable('eqp_calibration', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  calibrationNo: varchar('calibration_no', { length: 50 }).notNull(),
  equipmentId: bigint('equipment_id', { mode: 'number', unsigned: true }),
  equipmentCode: varchar('equipment_code', { length: 50 }).default(''),
  equipmentName: varchar('equipment_name', { length: 200 }).default(''),
  calibrationDate: date('calibration_date'),
  nextCalibrationDate: date('next_calibration_date'),
  calibrationOrg: varchar('calibration_org', { length: 200 }).default(''),
  calibrationResult: varchar('calibration_result', { length: 20 }).default('qualified'),
  certificateNo: varchar('certificate_no', { length: 50 }).default(''),
  calibrationCost: decimal('calibration_cost', { precision: 12, scale: 2 }).default('0.00'),
  remark: text('remark'),
  deleted: tinyint('deleted').default(0),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
    createBy: bigint('create_by', { mode: 'number', unsigned: true }), // 创建人
    status: tinyint('status'), // status
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
  ukCalibrationNo: uniqueIndex('uk_calibration_no').on(t.calibrationNo),
}));

export const eqpEquipment = mysqlTable('eqp_equipment', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  equipmentCode: varchar('equipment_code', { length: 50 }).notNull(),
  equipmentName: varchar('equipment_name', { length: 100 }).notNull(),
  equipmentType: tinyint('equipment_type'),
  brand: varchar('brand', { length: 50 }),
  model: varchar('model', { length: 50 }),
  serialNo: varchar('serial_no', { length: 50 }),
  workshopId: bigint('workshop_id', { mode: 'number', unsigned: true }),
  location: varchar('location', { length: 100 }),
  purchaseDate: date('purchase_date'),
  manufacturer: varchar('manufacturer', { length: 100 }),
  supplierId: bigint('supplier_id', { mode: 'number', unsigned: true }),
  warrantyExpire: date('warranty_expire'),
  ratedCapacity: decimal('rated_capacity', { precision: 18, scale: 4 }),
  currentStatus: tinyint('current_status').default(1),
  oee: decimal('oee', { precision: 5, scale: 2 }).default('0.00'),
  availability: decimal('availability', { precision: 5, scale: 2 }).default('0.00'),
  performance: decimal('performance', { precision: 5, scale: 2 }).default('0.00'),
  qualityRate: decimal('quality_rate', { precision: 5, scale: 2 }).default('0.00'),
  totalRunHours: decimal('total_run_hours', { precision: 10, scale: 2 }).default('0.00'),
  lastMaintenanceDate: date('last_maintenance_date'),
  nextMaintenanceDate: date('next_maintenance_date'),
  status: tinyint('status').default(1),
  remark: text('remark'),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
  createBy: bigint('create_by', { mode: 'number', unsigned: true }),
  deleted: tinyint('deleted').notNull().default(0),
    capacityPerHour: decimal('capacity_per_hour', { precision: 10, scale: 2 }).default('100.00'), // 每小时产能
    cumulativePrintCount: bigint('cumulative_print_count', { mode: 'number' }).default(0), // 累计产量
    cumulativeRunHours: decimal('cumulative_run_hours', { precision: 10, scale: 2 }).default('0.00'), // 累计运行时长（小时）
    expectedLifeYears: int('expected_life_years').default(10), // 预计使用年限（年）
    installDate: date('install_date'), // 安装日期
    maxColors: int('max_colors').default(1), // 最大支持色数
    purchasePrice: decimal('purchase_price', { precision: 12, scale: 2 }).default('0.00'), // 购置价格
    setupTimeMinutes: int('setup_time_minutes').default(30), // 换型准备时间
    workshop: varchar('workshop', { length: 50 }), // 所属车间
}, (t) => ({
  idxStatus: index('idx_status').on(t.status),
  idxType: index('idx_type').on(t.equipmentType),
  pk: primaryKey({ columns: [t.id] }),
  ukEquipmentCode: uniqueIndex('uk_equipment_code').on(t.equipmentCode),
}));

export const eqpMaintenancePlan = mysqlTable('eqp_maintenance_plan', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  planNo: varchar('plan_no', { length: 50 }).notNull(),
  equipmentId: bigint('equipment_id', { mode: 'number', unsigned: true }).notNull(),
  maintenanceType: tinyint('maintenance_type'),
  cycleType: tinyint('cycle_type'),
  cycleValue: int('cycle_value'),
  planDate: date('plan_date'),
  responsibleId: bigint('responsible_id', { mode: 'number', unsigned: true }),
  content: text('content'),
  status: tinyint('status').default(1),
  completeDate: date('complete_date'),
  remark: text('remark'),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
  deleted: tinyint('deleted').default(0),
    checklist: json('checklist'), // 检查项目清单（JSON 数组）
    createBy: bigint('create_by', { mode: 'number', unsigned: true }), // 创建人
    estimatedCost: decimal('estimated_cost', { precision: 10, scale: 2 }).default('0.00'), // 预计费用
    estimatedHours: decimal('estimated_hours', { precision: 5, scale: 2 }).default('4.00'), // 预计耗时（小时）
    lastExecutedDate: date('last_executed_date'), // 上次执行日期
    leadDays: int('lead_days').default(7), // 提前提醒天数
    nextExecuteDate: date('next_execute_date'), // 下次执行日期
    planName: varchar('plan_name', { length: 100 }), // 计划名称
    updateBy: bigint('update_by', { mode: 'number', unsigned: true }), // 更新人
}, (t) => ({
  idxEquipment: index('idx_equipment').on(t.equipmentId),
  idxStatus: index('idx_status').on(t.status),
  pk: primaryKey({ columns: [t.id] }),
  ukPlanNo: uniqueIndex('uk_plan_no').on(t.planNo),
}));

export const eqpMaintenanceRecord = mysqlTable('eqp_maintenance_record', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  recordNo: varchar('record_no', { length: 50 }).notNull(),
  planId: bigint('plan_id', { mode: 'number', unsigned: true }),
  equipmentId: bigint('equipment_id', { mode: 'number', unsigned: true }).notNull(),
  maintenanceType: tinyint('maintenance_type'),
  faultDesc: text('fault_desc'),
  maintenanceContent: text('maintenance_content'),
  startTime: datetime('start_time'),
  endTime: datetime('end_time'),
  downtimeHours: decimal('downtime_hours', { precision: 10, scale: 2 }).default('0.00'),
  cost: decimal('cost', { precision: 18, scale: 4 }).default('0.0000'),
  responsibleId: bigint('responsible_id', { mode: 'number', unsigned: true }),
  result: tinyint('result'),
  remark: text('remark'),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
  deleted: tinyint('deleted').default(0),
    createBy: bigint('create_by', { mode: 'number', unsigned: true }), // 创建人
    description: text('description'), // 维保内容描述
    maintenanceDate: date('maintenance_date'), // 维保日期
    partsReplaced: json('parts_replaced'), // 更换配件清单（JSON 数组）
    runHoursAfter: decimal('run_hours_after', { precision: 10, scale: 2 }), // 维保后运行时长
    runHoursBefore: decimal('run_hours_before', { precision: 10, scale: 2 }), // 维保前运行时长
    status: tinyint('status').default(1), // 状态：1=已完成 2=进行中 3=已取消
    technicianName: varchar('technician_name', { length: 50 }), // 技术员姓名
    updateBy: bigint('update_by', { mode: 'number', unsigned: true }), // 更新人
}, (t) => ({
  idxEquipment: index('idx_equipment').on(t.equipmentId),
  idxPlan: index('idx_plan').on(t.planId),
  pk: primaryKey({ columns: [t.id] }),
  ukRecordNo: uniqueIndex('uk_record_no').on(t.recordNo),
}));

export const eqpRepair = mysqlTable('eqp_repair', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  repairNo: varchar('repair_no', { length: 50 }).notNull(),
  equipmentId: bigint('equipment_id', { mode: 'number', unsigned: true }),
  equipmentCode: varchar('equipment_code', { length: 50 }).default(''),
  equipmentName: varchar('equipment_name', { length: 200 }).default(''),
  faultDate: date('fault_date'),
  faultDesc: text('fault_desc'),
  repairType: varchar('repair_type', { length: 20 }).default('corrective'),
  repairPerson: varchar('repair_person', { length: 100 }).default(''),
  remark: text('remark'),
  deleted: tinyint('deleted').default(0),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
    createBy: bigint('create_by', { mode: 'number', unsigned: true }), // 创建人
    repairCost: decimal('repair_cost', { precision: 12, scale: 2 }).default('0.00'), // 维修成本
    repairEndTime: datetime('repair_end_time'), // 维修结束时间
    repairResult: varchar('repair_result', { length: 255 }), // 维修结果
    repairStartTime: datetime('repair_start_time'), // 维修开始时间
    status: tinyint('status').default(0), // 维修状态 0待修1维修中2已完成3已关闭
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
  ukRepairNo: uniqueIndex('uk_repair_no').on(t.repairNo),
}));

export const eqpScrap = mysqlTable('eqp_scrap', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  scrapNo: varchar('scrap_no', { length: 50 }).notNull(),
  equipmentId: bigint('equipment_id', { mode: 'number', unsigned: true }),
  equipmentCode: varchar('equipment_code', { length: 50 }).default(''),
  equipmentName: varchar('equipment_name', { length: 200 }).default(''),
  scrapDate: date('scrap_date'),
  scrapReason: text('scrap_reason'),
  originalValue: decimal('original_value', { precision: 12, scale: 2 }).default('0.00'),
  netValue: decimal('net_value', { precision: 12, scale: 2 }).default('0.00'),
  approvalPerson: varchar('approval_person', { length: 100 }).default(''),
  remark: text('remark'),
  deleted: tinyint('deleted').default(0),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
    createBy: bigint('create_by', { mode: 'number', unsigned: true }), // 创建人
    status: tinyint('status'), // status
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
  ukScrapNo: uniqueIndex('uk_scrap_no').on(t.scrapNo),
}));

