// AUTO-GENERATED by scripts/_audit/gen_pur.cjs (2026-08-26)
// 来源: live information_schema. 建模 9 张核心 pur_* 缺失表（含 5 张 *_deprecated 废弃表，真实存在须建模以免护栏误判 DROP）。
// 跨域 FK / 自引用 FK 以注释保留；内部 pur_* FK 实写。
import { mysqlTable, int, bigint, smallint, mediumint, tinyint, varchar, char, decimal, float, double, text, date, datetime, timestamp, time, json, mysqlEnum, primaryKey, index, uniqueIndex, foreignKey } from 'drizzle-orm/mysql-core';
import { sql } from 'drizzle-orm';

export const purOrderDeprecated = mysqlTable('pur_order_deprecated', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  orderNo: varchar('order_no', { length: 50 }).notNull(),
  orderDate: date('order_date'),
  supplierId: bigint('supplier_id', { mode: 'number', unsigned: true }).notNull(),
  contactName: varchar('contact_name', { length: 50 }),
  contactPhone: varchar('contact_phone', { length: 20 }),
  deliveryAddress: varchar('delivery_address', { length: 255 }),
  totalAmount: decimal('total_amount', { precision: 18, scale: 4 }).default('0.0000'),
  taxAmount: decimal('tax_amount', { precision: 18, scale: 4 }).default('0.0000'),
  totalWithTax: decimal('total_with_tax', { precision: 18, scale: 4 }).default('0.0000'),
  currency: varchar('currency', { length: 10 }).default('CNY'),
  exchangeRate: decimal('exchange_rate', { precision: 10, scale: 4 }).default('1.0000'),
  paymentTerms: varchar('payment_terms', { length: 100 }),
  deliveryDate: date('delivery_date'),
  settlementMethod: varchar('settlement_method', { length: 50 }),
  status: tinyint('status').default(1),
  remark: text('remark'),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
  createBy: bigint('create_by', { mode: 'number', unsigned: true }),
  updateBy: bigint('update_by', { mode: 'number', unsigned: true }),
  deleted: tinyint('deleted').default(0),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
  ukOrderNo: uniqueIndex('uk_order_no').on(t.orderNo),
}));

export const purPurchaseReconciliationWriteoff = mysqlTable('pur_purchase_reconciliation_writeoff', {
  id: bigint('id', { mode: 'number' }).autoincrement().notNull(),
  reconciliationId: bigint('reconciliation_id', { mode: 'number' }).notNull(),
  payableId: bigint('payable_id', { mode: 'number' }).notNull(),
  amount: decimal('amount', { precision: 14, scale: 2 }).notNull(),
  writeOffDate: date('write_off_date').notNull(),
  remark: varchar('remark', { length: 512 }).notNull().default(''),
  createBy: bigint('create_by', { mode: 'number' }),
  createTime: datetime('create_time').notNull().default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  idxPayableId: index('idx_payable_id').on(t.payableId),
  idxReconciliationId: index('idx_reconciliation_id').on(t.reconciliationId),
  pk: primaryKey({ columns: [t.id] }),
}));

export const purReceiptDeprecated = mysqlTable('pur_receipt_deprecated', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  receiptNo: varchar('receipt_no', { length: 50 }).notNull(),
  receiptDate: date('receipt_date'),
  orderId: bigint('order_id', { mode: 'number', unsigned: true }),
  supplierId: bigint('supplier_id', { mode: 'number', unsigned: true }).notNull(),
  warehouseId: bigint('warehouse_id', { mode: 'number', unsigned: true }).notNull(),
  totalAmount: decimal('total_amount', { precision: 18, scale: 4 }).default('0.0000'),
  inspectorId: bigint('inspector_id', { mode: 'number', unsigned: true }),
  inspectionResult: tinyint('inspection_result'),
  status: tinyint('status').default(1),
  remark: text('remark'),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
  createBy: bigint('create_by', { mode: 'number', unsigned: true }),
}, (t) => ({
  idxInspector: index('idx_inspector').on(t.inspectorId),
  idxOrder: index('idx_order').on(t.orderId),
  idxSupplier: index('idx_supplier').on(t.supplierId),
  idxWarehouse: index('idx_warehouse').on(t.warehouseId),
  pk: primaryKey({ columns: [t.id] }),
  ukReceiptNo: uniqueIndex('uk_receipt_no').on(t.receiptNo),
}));

export const purReceiptDetailDeprecated = mysqlTable('pur_receipt_detail_deprecated', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  receiptId: bigint('receipt_id', { mode: 'number', unsigned: true }).notNull(),
  materialId: bigint('material_id', { mode: 'number', unsigned: true }).notNull(),
  orderDetailId: bigint('order_detail_id', { mode: 'number', unsigned: true }),
  quantity: decimal('quantity', { precision: 18, scale: 4 }).notNull(),
  unit: varchar('unit', { length: 20 }),
  unitPrice: decimal('unit_price', { precision: 18, scale: 4 }),
  amount: decimal('amount', { precision: 18, scale: 4 }),
  batchNo: varchar('batch_no', { length: 50 }),
  productionDate: date('production_date'),
  expiryDate: date('expiry_date'),
  locationCode: varchar('location_code', { length: 50 }),
  remark: varchar('remark', { length: 255 }),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  idxMaterial: index('idx_material').on(t.materialId),
  idxOrderDetail: index('idx_order_detail').on(t.orderDetailId),
  idxReceipt: index('idx_receipt').on(t.receiptId),
  pk: primaryKey({ columns: [t.id] }),
}));

export const purRequest = mysqlTable('pur_request', {
  id: int('id', { unsigned: true }).autoincrement().notNull(),
  requestNo: varchar('request_no', { length: 50 }).notNull(),
  requestDate: date('request_date'),
  requestType: varchar('request_type', { length: 20 }).default('material'),
  requestDeptId: int('request_dept_id', { unsigned: true }),
  requestDept: varchar('request_dept', { length: 100 }),
  requesterId: bigint('requester_id', { mode: 'number', unsigned: true }),
  requesterName: varchar('requester_name', { length: 50 }),
  reviewerId: int('reviewer_id', { unsigned: true }),
  reviewerName: varchar('reviewer_name', { length: 50 }),
  approverId: bigint('approver_id', { mode: 'number', unsigned: true }),
  approverName: varchar('approver_name', { length: 50 }),
  totalAmount: decimal('total_amount', { precision: 14, scale: 2 }).default('0.00'),
  currency: varchar('currency', { length: 10 }).default('CNY'),
  status: tinyint('status').default(0),
  priority: tinyint('priority').default(1),
  expectedDate: date('expected_date'),
  supplierName: varchar('supplier_name', { length: 100 }),
  remark: text('remark'),
  createBy: int('create_by', { unsigned: true }),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateBy: int('update_by', { unsigned: true }),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
  deleted: tinyint('deleted').notNull().default(0),
}, (t) => ({
  idxRequestDate: index('idx_request_date').on(t.requestDate),
  idxRequestDept: index('idx_request_dept').on(t.requestDeptId),
  idxRequester: index('idx_requester').on(t.requesterId),
  idxStatus: index('idx_status').on(t.status),
  pk: primaryKey({ columns: [t.id] }),
  ukRequestNo: uniqueIndex('uk_request_no').on(t.requestNo),
}));

export const purRequestDetail = mysqlTable('pur_request_detail', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  requestId: bigint('request_id', { mode: 'number', unsigned: true }).notNull(),
  materialId: bigint('material_id', { mode: 'number', unsigned: true }).notNull(),
  quantity: decimal('quantity', { precision: 18, scale: 4 }).notNull(),
  unit: varchar('unit', { length: 20 }),
  requiredDate: date('required_date'),
  purpose: varchar('purpose', { length: 255 }),
  remark: varchar('remark', { length: 255 }),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  deleted: tinyint('deleted').notNull().default(0),
}, (t) => ({
  idxMaterial: index('idx_material').on(t.materialId),
  idxRequest: index('idx_request').on(t.requestId),
  pk: primaryKey({ columns: [t.id] }),
}));

export const purRequestItem = mysqlTable('pur_request_item', {
  id: int('id', { unsigned: true }).autoincrement().notNull(),
  requestId: int('request_id', { unsigned: true }).notNull(),
  lineNo: int('line_no', { unsigned: true }).notNull(),
  materialId: int('material_id', { unsigned: true }),
  materialCode: varchar('material_code', { length: 50 }),
  materialName: varchar('material_name', { length: 200 }),
  materialSpec: varchar('material_spec', { length: 500 }),
  materialUnit: varchar('material_unit', { length: 20 }),
  quantity: decimal('quantity', { precision: 14, scale: 3 }).default('0.000'),
  price: decimal('price', { precision: 14, scale: 4 }).default('0.0000'),
  amount: decimal('amount', { precision: 14, scale: 2 }).default('0.00'),
  supplierName: varchar('supplier_name', { length: 100 }),
  expectedDate: date('expected_date'),
  remark: text('remark'),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
  deleted: tinyint('deleted').default(0),
}, (t) => ({
  idxMaterialId: index('idx_material_id').on(t.materialId),
  idxRequest: index('idx_request').on(t.requestId),
  pk: primaryKey({ columns: [t.id] }),
}));

export const purSupplierMaterial = mysqlTable('pur_supplier_material', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  supplierId: bigint('supplier_id', { mode: 'number', unsigned: true }).notNull(),
  materialId: bigint('material_id', { mode: 'number', unsigned: true }).notNull(),
  supplyPrice: decimal('supply_price', { precision: 18, scale: 4 }),
  minOrderQty: decimal('min_order_qty', { precision: 18, scale: 4 }),
  leadTime: int('lead_time'),
  isDefault: tinyint('is_default').default(0),
  status: tinyint('status').default(1),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
  deleted: tinyint('deleted').notNull().default(0),
}, (t) => ({
  idxMaterial: index('idx_material').on(t.materialId),
  pk: primaryKey({ columns: [t.id] }),
  ukSupplierMaterial: uniqueIndex('uk_supplier_material').on(t.supplierId, t.materialId),
}));

export const purOrderDetailDeprecated = mysqlTable('pur_order_detail_deprecated', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  orderId: bigint('order_id', { mode: 'number', unsigned: true }).notNull(),
  materialId: bigint('material_id', { mode: 'number', unsigned: true }).notNull(),
  quantity: decimal('quantity', { precision: 18, scale: 4 }).notNull(),
  unit: varchar('unit', { length: 20 }),
  unitPrice: decimal('unit_price', { precision: 18, scale: 4 }),
  taxRate: decimal('tax_rate', { precision: 5, scale: 2 }).default('0.00'),
  amount: decimal('amount', { precision: 18, scale: 4 }),
  taxAmount: decimal('tax_amount', { precision: 18, scale: 4 }),
  totalAmount: decimal('total_amount', { precision: 18, scale: 4 }),
  receivedQty: decimal('received_qty', { precision: 18, scale: 4 }).default('0.0000'),
  deliveryDate: date('delivery_date'),
  remark: varchar('remark', { length: 255 }),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
  fkPurOrderDetailOrder: foreignKey({ columns: [t.orderId], foreignColumns: [purOrderDeprecated.id] }),
}));

