// AUTO-GENERATED by scripts/_audit/gen_misc.cjs (2026-08-26)
// 域: outsource ｜ 来源: live information_schema ｜ 建模 5 张核心缺失表。
// 导出名冲突自动规避（追加 Gen 后缀）；跨域 FK 注释保留；内部/已建模 FK 实写。
import { mysqlTable, int, bigint, smallint, mediumint, tinyint, varchar, char, decimal, float, double, text, date, datetime, timestamp, time, json, mysqlEnum, primaryKey, index, uniqueIndex, foreignKey } from 'drizzle-orm/mysql-core';
import { sql } from 'drizzle-orm';

export const outsourceIssue = mysqlTable('outsource_issue', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  issueNo: varchar('issue_no', { length: 50 }).notNull(),
  outsourceOrderId: bigint('outsource_order_id', { mode: 'number', unsigned: true }),
  outsourceOrderNo: varchar('outsource_order_no', { length: 50 }),
  warehouseId: bigint('warehouse_id', { mode: 'number', unsigned: true }),
  issueDate: date('issue_date'),
  status: tinyint('status').default(1),
  operatorName: varchar('operator_name', { length: 100 }).default(''),
  remark: text('remark'),
  deleted: tinyint('deleted').default(0),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
  ukIssueNo: uniqueIndex('uk_issue_no').on(t.issueNo),
}));

export const outsourceIssueItem = mysqlTable('outsource_issue_item', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  issueId: bigint('issue_id', { mode: 'number', unsigned: true }).notNull(),
  materialId: bigint('material_id', { mode: 'number', unsigned: true }),
  materialCode: varchar('material_code', { length: 50 }).default(''),
  materialName: varchar('material_name', { length: 200 }).default(''),
  quantity: decimal('quantity', { precision: 12, scale: 2 }).default('0.00'),
  unit: varchar('unit', { length: 20 }).default(''),
  batchNo: varchar('batch_no', { length: 50 }).default(''),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
}));

export const outsourceOrder = mysqlTable('outsource_order', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  orderNo: varchar('order_no', { length: 50 }).notNull(),
  workOrderId: bigint('work_order_id', { mode: 'number', unsigned: true }),
  workOrderNo: varchar('work_order_no', { length: 50 }),
  supplierId: bigint('supplier_id', { mode: 'number', unsigned: true }),
  supplierName: varchar('supplier_name', { length: 200 }).default(''),
  productId: bigint('product_id', { mode: 'number', unsigned: true }),
  productCode: varchar('product_code', { length: 50 }).default(''),
  productName: varchar('product_name', { length: 200 }).default(''),
  planQty: decimal('plan_qty', { precision: 12, scale: 2 }).default('0.00'),
  unit: varchar('unit', { length: 20 }).default(''),
  unitPrice: decimal('unit_price', { precision: 12, scale: 2 }).default('0.00'),
  totalAmount: decimal('total_amount', { precision: 12, scale: 2 }).default('0.00'),
  deliveryDate: date('delivery_date'),
  outsourceType: varchar('outsource_type', { length: 20 }).default('process'),
  processName: varchar('process_name', { length: 200 }).default(''),
  status: tinyint('status').default(0),
  remark: text('remark'),
  deleted: tinyint('deleted').default(0),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
  ukOrderNo: uniqueIndex('uk_order_no').on(t.orderNo),
}));

export const outsourceReceive = mysqlTable('outsource_receive', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  receiveNo: varchar('receive_no', { length: 50 }).notNull(),
  outsourceOrderId: bigint('outsource_order_id', { mode: 'number', unsigned: true }),
  outsourceOrderNo: varchar('outsource_order_no', { length: 50 }),
  warehouseId: bigint('warehouse_id', { mode: 'number', unsigned: true }),
  receiveDate: date('receive_date'),
  receiveQty: decimal('receive_qty', { precision: 12, scale: 2 }).default('0.00'),
  qualifiedQty: decimal('qualified_qty', { precision: 12, scale: 2 }).default('0.00'),
  defectiveQty: decimal('defective_qty', { precision: 12, scale: 2 }).default('0.00'),
  qcStatus: varchar('qc_status', { length: 20 }).default('pending'),
  status: tinyint('status').default(1),
  operatorName: varchar('operator_name', { length: 100 }).default(''),
  remark: text('remark'),
  deleted: tinyint('deleted').default(0),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
  ukReceiveNo: uniqueIndex('uk_receive_no').on(t.receiveNo),
}));

export const outsourceSettlement = mysqlTable('outsource_settlement', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  settlementNo: varchar('settlement_no', { length: 50 }).notNull(),
  outsourceOrderId: bigint('outsource_order_id', { mode: 'number', unsigned: true }),
  outsourceOrderNo: varchar('outsource_order_no', { length: 50 }),
  supplierId: bigint('supplier_id', { mode: 'number', unsigned: true }),
  supplierName: varchar('supplier_name', { length: 200 }).default(''),
  settlementDate: date('settlement_date'),
  settlementQty: decimal('settlement_qty', { precision: 12, scale: 2 }).default('0.00'),
  unitPrice: decimal('unit_price', { precision: 12, scale: 2 }).default('0.00'),
  settlementAmount: decimal('settlement_amount', { precision: 12, scale: 2 }).default('0.00'),
  deductAmount: decimal('deduct_amount', { precision: 12, scale: 2 }).default('0.00'),
  actualAmount: decimal('actual_amount', { precision: 12, scale: 2 }).default('0.00'),
  paymentStatus: varchar('payment_status', { length: 20 }).default('unpaid'),
  status: tinyint('status').default(0),
  remark: text('remark'),
  deleted: tinyint('deleted').default(0),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
  ukSettlementNo: uniqueIndex('uk_settlement_no').on(t.settlementNo),
}));

