import { sysUser } from './system';
import { salOrder } from './sales';
import { crmCustomer } from './_gen_crm';
import { prdWorkOrder } from './production';
// AUTO-GENERATED by scripts/_audit/gen_warehouse_missing.cjs (Phase 0, v2)
// 来源: live information_schema. 生成于 2026-08-25.
// 建模 28 张核心 inv_* 表；_bak* 备份表已排除；跨域 FK / 自引用 FK 以注释保留。
import {
  mysqlTable,
  int,
  bigint,
  smallint,
  mediumint,
  tinyint,
  varchar,
  char,
  decimal,
  float,
  double,
  text,
  date,
  datetime,
  timestamp,
  time,
  json,
  mysqlEnum,
  primaryKey,
  index,
  uniqueIndex,
  foreignKey,
} from 'drizzle-orm/mysql-core';
import { sql } from 'drizzle-orm';
import {
  invMaterial,
  invInventoryBatch,
  invInboundOrders,
  invInboundItems,
  invWarehouse,
  invInventory,
  invOutboundOrders,
  invOutboundItems,
  invTransferOrders,
  invStocktaking,
} from './warehouse';

export const invAuxiliaryInventory = mysqlTable(
  'inv_auxiliary_inventory',
  {
    id: int('id').autoincrement().notNull(),
    auxCode: varchar('aux_code', { length: 100 }),
    auxName: varchar('aux_name', { length: 255 }),
    specification: varchar('specification', { length: 255 }),
    category: varchar('category', { length: 100 }),
    unit: varchar('unit', { length: 50 }),
    warehouse: varchar('warehouse', { length: 100 }),
    location: varchar('location', { length: 100 }),
    supplier: varchar('supplier', { length: 255 }),
    openingBalance: decimal('opening_balance', { precision: 18, scale: 4 }).default('0.0000'),
    totalIn: decimal('total_in', { precision: 18, scale: 4 }).default('0.0000'),
    totalOut: decimal('total_out', { precision: 18, scale: 4 }).default('0.0000'),
    currentBalance: decimal('current_balance', { precision: 18, scale: 4 }).default('0.0000'),
    sourceFile: varchar('source_file', { length: 255 }),
    sourceSheet: varchar('source_sheet', { length: 100 }),
    importTime: datetime('import_time').default(sql`CURRENT_TIMESTAMP`),
    remarks: text('remarks'),
  },
  (t) => ({
    idxAuxCode: index('idx_aux_code').on(t.auxCode),
    idxAuxName: index('idx_aux_name').on(t.auxName),
    idxSupplier: index('idx_supplier').on(t.supplier),
    pk: primaryKey({ columns: [t.id] }),
  })
);

export const invCuttingDetail = mysqlTable(
  'inv_cutting_detail',
  {
    id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
    recordId: bigint('record_id', { mode: 'number', unsigned: true }).notNull(),
    newLabelId: bigint('new_label_id', { mode: 'number', unsigned: true }).notNull(),
    newLabelNo: varchar('new_label_no', { length: 50 }).notNull(),
    cutWidth: decimal('cut_width', { precision: 18, scale: 2 }),
    sequence: int('sequence').default(0),
    createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  },
  (t) => ({
    idxNewLabel: index('idx_new_label').on(t.newLabelId),
    idxRecordId: index('idx_record_id').on(t.recordId),
    pk: primaryKey({ columns: [t.id] }),
  })
);

export const invCuttingRecord = mysqlTable(
  'inv_cutting_record',
  {
    id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
    recordNo: varchar('record_no', { length: 50 }).notNull(),
    sourceLabelId: bigint('source_label_id', { mode: 'number', unsigned: true }).notNull(),
    sourceLabelNo: varchar('source_label_no', { length: 50 }).notNull(),
    cutWidthStr: varchar('cut_width_str', { length: 200 }),
    originalWidth: decimal('original_width', { precision: 18, scale: 2 }),
    cutTotalWidth: decimal('cut_total_width', { precision: 18, scale: 2 }),
    remainWidth: decimal('remain_width', { precision: 18, scale: 2 }),
    operatorId: bigint('operator_id', { mode: 'number', unsigned: true }),
    operatorName: varchar('operator_name', { length: 50 }),
    cutTime: datetime('cut_time').default(sql`CURRENT_TIMESTAMP`),
    remark: varchar('remark', { length: 500 }),
    status: tinyint('status').default(1),
    createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  },
  (t) => ({
    idxCutTime: index('idx_cut_time').on(t.cutTime),
    idxSourceLabel: index('idx_source_label').on(t.sourceLabelId),
    pk: primaryKey({ columns: [t.id] }),
    ukRecordNo: uniqueIndex('uk_record_no').on(t.recordNo),
  })
);

export const invFifoOverrideLog = mysqlTable(
  'inv_fifo_override_log',
  {
    id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
    materialId: bigint('material_id', { mode: 'number', unsigned: true }).notNull(),
    recommendedBatchNo: varchar('recommended_batch_no', { length: 50 }),
    actualBatchNo: varchar('actual_batch_no', { length: 50 }),
    requisitionId: bigint('requisition_id', { mode: 'number', unsigned: true }),
    reason: varchar('reason', { length: 255 }).notNull(),
    operatorId: bigint('operator_id', { mode: 'number', unsigned: true }),
    operatorName: varchar('operator_name', { length: 50 }),
    approveId: bigint('approve_id', { mode: 'number', unsigned: true }),
    approveName: varchar('approve_name', { length: 50 }),
    status: tinyint('status').default(0),
    createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
    deleted: tinyint('deleted').notNull().default(0),
  },
  (t) => ({
    idxApprove: index('idx_approve').on(t.approveId),
    idxMaterial: index('idx_material').on(t.materialId),
    idxOperator: index('idx_operator').on(t.operatorId),
    idxRequisition: index('idx_requisition').on(t.requisitionId),
    pk: primaryKey({ columns: [t.id] }),
  })
);

export const invInboundLabel = mysqlTable(
  'inv_inbound_label',
  {
    id: bigint('id', { mode: 'number' }).autoincrement().notNull(),
    labelId: varchar('label_id', { length: 50 }).notNull(),
    orderId: bigint('order_id', { mode: 'number' }),
    orderNo: varchar('order_no', { length: 50 }),
    itemId: bigint('item_id', { mode: 'number' }),
    purchaseOrderNo: varchar('purchase_order_no', { length: 50 }),
    supplierName: varchar('supplier_name', { length: 200 }),
    inboundDate: date('inbound_date'),
    warehouseCode: varchar('warehouse_code', { length: 50 }),
    materialCode: varchar('material_code', { length: 50 }).notNull(),
    materialName: varchar('material_name', { length: 200 }).notNull(),
    specification: varchar('specification', { length: 200 }),
    width: decimal('width', { precision: 18, scale: 4 }).default('0.0000'),
    batchNo: varchar('batch_no', { length: 50 }),
    qty: decimal('qty', { precision: 18, scale: 4 }).notNull().default('0.0000'),
    unit: varchar('unit', { length: 20 }).notNull().default('件'),
    isRawMaterial: tinyint('is_raw_material').notNull().default(0),
    packageQty: int('package_qty').default(0),
    labelQty: int('label_qty').default(1),
    labelStatus: varchar('label_status', { length: 20 }).notNull().default('generated'),
    auditStatus: tinyint('audit_status').default(0),
    operatorId: bigint('operator_id', { mode: 'number' }),
    operatorName: varchar('operator_name', { length: 50 }),
    auditorId: bigint('auditor_id', { mode: 'number' }),
    auditorName: varchar('auditor_name', { length: 50 }),
    auditTime: datetime('audit_time'),
    colorCode: varchar('color_code', { length: 50 }),
    mixedMaterialRemark: varchar('mixed_material_remark', { length: 500 }),
    machineNo: varchar('machine_no', { length: 50 }),
    remark: varchar('remark', { length: 500 }),
    deleted: tinyint('deleted').notNull().default(0),
    createTime: datetime('create_time')
      .notNull()
      .default(sql`CURRENT_TIMESTAMP`),
    updateTime: datetime('update_time')
      .notNull()
      .default(sql`CURRENT_TIMESTAMP`),
  },
  (t) => ({
    idxBatchNo: index('idx_batch_no').on(t.batchNo),
    idxLabelStatus: index('idx_label_status').on(t.labelStatus),
    idxMaterialCode: index('idx_material_code').on(t.materialCode),
    idxOrderNo: index('idx_order_no').on(t.orderNo),
    pk: primaryKey({ columns: [t.id] }),
    ukLabelId: uniqueIndex('uk_label_id').on(t.labelId),
  })
);

export const invInventoryLog = mysqlTable(
  'inv_inventory_log',
  {
    id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
    warehouseId: int('warehouse_id', { unsigned: true }),
    materialId: int('material_id', { unsigned: true }),
    changeType: varchar('change_type', { length: 20 }),
    changeQty: decimal('change_qty', { precision: 12, scale: 3 }).default('0.000'),
    orderNo: varchar('order_no', { length: 50 }),
    remark: text('remark'),
    createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
    batchNo: varchar('batch_no', { length: 50 }),
    transType: varchar('trans_type', { length: 20 }),
    quantity: decimal('quantity', { precision: 18, scale: 4 }),
    beforeQty: decimal('before_qty', { precision: 18, scale: 4 }),
    afterQty: decimal('after_qty', { precision: 18, scale: 4 }),
    unit: varchar('unit', { length: 20 }),
    sourceType: varchar('source_type', { length: 50 }),
    sourceNo: varchar('source_no', { length: 50 }),
    operationType: tinyint('operation_type'),
    operationQty: decimal('operation_qty', { precision: 18, scale: 4 }),
    businessType: varchar('business_type', { length: 50 }),
    businessNo: varchar('business_no', { length: 50 }),
    operatorId: bigint('operator_id', { mode: 'number', unsigned: true }),
  },
  (t) => ({
    idxCreateTime: index('idx_create_time').on(t.createTime),
    idxMaterial: index('idx_material').on(t.materialId),
    idxWarehouse: index('idx_warehouse').on(t.warehouseId),
    pk: primaryKey({ columns: [t.id] }),
  })
);

export const invInventoryTransaction = mysqlTable(
  'inv_inventory_transaction',
  {
    id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
    transNo: varchar('trans_no', { length: 50 }).notNull(),
    transType: mysqlEnum('trans_type', [
      'in',
      'out',
      'transfer',
      'adjust',
      'return',
    ] as const).notNull(),
    sourceType: varchar('source_type', { length: 20 }),
    sourceId: bigint('source_id', { mode: 'number', unsigned: true }),
    sourceLineId: bigint('source_line_id', { mode: 'number', unsigned: true }),
    materialId: bigint('material_id', { mode: 'number', unsigned: true }),
    materialCode: varchar('material_code', { length: 50 }),
    batchNo: varchar('batch_no', { length: 50 }),
    warehouseId: bigint('warehouse_id', { mode: 'number', unsigned: true }),
    locationId: bigint('location_id', { mode: 'number', unsigned: true }),
    quantity: decimal('quantity', { precision: 14, scale: 3 }).default('0.000'),
    unitCost: decimal('unit_cost', { precision: 14, scale: 4 }).default('0.0000'),
    totalCost: decimal('total_cost', { precision: 14, scale: 2 }).default('0.00'),
    unitPrice: decimal('unit_price', { precision: 14, scale: 4 }).default('0.0000'),
    totalAmount: decimal('total_amount', { precision: 14, scale: 2 }).default('0.00'),
    referenceNo: varchar('reference_no', { length: 100 }),
    remark: text('remark'),
    createBy: bigint('create_by', { mode: 'number', unsigned: true }),
    createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
    accountDr: varchar('account_dr', { length: 50 }),
    accountCr: varchar('account_cr', { length: 50 }),
    sourceNo: varchar('source_no', { length: 100 }).default(''),
  },
  (t) => ({
    idxBatch: index('idx_batch').on(t.batchNo),
    idxCreateTime: index('idx_create_time').on(t.createTime),
    idxMaterial: index('idx_material').on(t.materialId),
    idxSource: index('idx_source').on(t.sourceType, t.sourceId),
    idxTransType: index('idx_trans_type').on(t.transType),
    idxWarehouse: index('idx_warehouse').on(t.warehouseId),
    pk: primaryKey({ columns: [t.id] }),
    ukTransNo: uniqueIndex('uk_trans_no').on(t.transNo),
  })
);

export const invInventoryTransactionLog = mysqlTable(
  'inv_inventory_transaction_log',
  {
    id: int('id').autoincrement().notNull(),
    transactionType: varchar('transaction_type', { length: 50 }),
    itemType: varchar('item_type', { length: 50 }),
    itemId: int('item_id'),
    itemCode: varchar('item_code', { length: 100 }),
    itemName: varchar('item_name', { length: 255 }),
    quantity: decimal('quantity', { precision: 18, scale: 4 }),
    transactionDate: date('transaction_date'),
    referenceNo: varchar('reference_no', { length: 100 }),
    warehouse: varchar('warehouse', { length: 100 }),
    location: varchar('location', { length: 100 }),
    operator: varchar('operator', { length: 100 }),
    sourceFile: varchar('source_file', { length: 255 }),
    createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
    remarks: text('remarks'),
  },
  (t) => ({
    idxItemType: index('idx_item_type').on(t.itemType),
    idxTransactionDate: index('idx_transaction_date').on(t.transactionDate),
    idxTransactionType: index('idx_transaction_type').on(t.transactionType),
    pk: primaryKey({ columns: [t.id] }),
  })
);

export const invLocation = mysqlTable(
  'inv_location',
  {
    id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
    locationCode: varchar('location_code', { length: 50 }).notNull(),
    locationName: varchar('location_name', { length: 100 }).notNull(),
    warehouseId: bigint('warehouse_id', { mode: 'number', unsigned: true }).notNull(),
    zone: varchar('zone', { length: 50 }),
    rowNo: varchar('row_no', { length: 20 }),
    columnNo: varchar('column_no', { length: 20 }),
    layerNo: varchar('layer_no', { length: 20 }),
    locationType: tinyint('location_type').default(1),
    status: tinyint('status').default(1),
    remark: text('remark'),
    createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
    updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
    deleted: tinyint('deleted').default(0),
  },
  (t) => ({
    idxWarehouse: index('idx_warehouse').on(t.warehouseId),
    pk: primaryKey({ columns: [t.id] }),
    ukLocationCode: uniqueIndex('uk_location_code').on(t.locationCode),
  })
);

// SKIP-FK (self-ref): inv_material_category.parentId -> inv_material_category.id
export const invMaterialCategory = mysqlTable(
  'inv_material_category',
  {
    id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
    parentId: bigint('parent_id', { mode: 'number', unsigned: true }),
    categoryCode: varchar('category_code', { length: 50 }).notNull(),
    categoryName: varchar('category_name', { length: 100 }).notNull(),
    sortOrder: int('sort_order').default(0),
    status: tinyint('status').default(1),
    createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
    updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
    deleted: tinyint('deleted').notNull().default(0),
    createBy: bigint('create_by', { mode: 'number', unsigned: true }),
    updateBy: bigint('update_by', { mode: 'number', unsigned: true }),
    categoryType: tinyint('category_type'),
    remark: varchar('remark', { length: 255 }),
  },
  (t) => ({
    idxParent: index('idx_parent').on(t.parentId),
    pk: primaryKey({ columns: [t.id] }),
    ukCategoryCode: uniqueIndex('uk_category_code').on(t.categoryCode),
  })
);

export const invMaterialInventory = mysqlTable(
  'inv_material_inventory',
  {
    id: int('id').autoincrement().notNull(),
    materialCode: varchar('material_code', { length: 100 }),
    materialName: varchar('material_name', { length: 255 }),
    specification: varchar('specification', { length: 255 }),
    category: varchar('category', { length: 100 }),
    materialType: varchar('material_type', { length: 50 }),
    unit: varchar('unit', { length: 50 }),
    warehouse: varchar('warehouse', { length: 100 }),
    location: varchar('location', { length: 100 }),
    supplier: varchar('supplier', { length: 255 }),
    openingBalance: decimal('opening_balance', { precision: 18, scale: 4 }).default('0.0000'),
    totalIn: decimal('total_in', { precision: 18, scale: 4 }).default('0.0000'),
    totalOut: decimal('total_out', { precision: 18, scale: 4 }).default('0.0000'),
    currentBalance: decimal('current_balance', { precision: 18, scale: 4 }).default('0.0000'),
    safetyStock: decimal('safety_stock', { precision: 18, scale: 4 }).default('0.0000'),
    sourceFile: varchar('source_file', { length: 255 }),
    sourceSheet: varchar('source_sheet', { length: 100 }),
    importTime: datetime('import_time').default(sql`CURRENT_TIMESTAMP`),
    remarks: text('remarks'),
  },
  (t) => ({
    idxCategory: index('idx_category').on(t.category),
    idxMaterialCode: index('idx_material_code').on(t.materialCode),
    idxMaterialName: index('idx_material_name').on(t.materialName),
    idxSupplier: index('idx_supplier').on(t.supplier),
    pk: primaryKey({ columns: [t.id] }),
  })
);

export const invMaterialLabel = mysqlTable(
  'inv_material_label',
  {
    id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
    labelNo: varchar('label_no', { length: 50 }).notNull(),
    qrCode: varchar('qr_code', { length: 255 }),
    purchaseOrderNo: varchar('purchase_order_no', { length: 50 }),
    supplierName: varchar('supplier_name', { length: 200 }),
    receiveDate: date('receive_date'),
    materialCode: varchar('material_code', { length: 50 }).notNull(),
    materialName: varchar('material_name', { length: 200 }),
    specification: varchar('specification', { length: 200 }),
    unit: varchar('unit', { length: 20 }),
    batchNo: varchar('batch_no', { length: 50 }),
    quantity: decimal('quantity', { precision: 18, scale: 4 }).default('0.0000'),
    packageQty: decimal('package_qty', { precision: 18, scale: 4 }).default('0.0000'),
    width: decimal('width', { precision: 18, scale: 2 }),
    lengthPerRoll: decimal('length_per_roll', { precision: 18, scale: 2 }),
    remark: varchar('remark', { length: 500 }),
    colorCode: varchar('color_code', { length: 50 }),
    mixRemark: varchar('mix_remark', { length: 500 }),
    warehouseId: bigint('warehouse_id', { mode: 'number', unsigned: true }),
    locationId: bigint('location_id', { mode: 'number', unsigned: true }),
    isMainMaterial: tinyint('is_main_material').default(0),
    isUsed: tinyint('is_used').default(0),
    isCut: tinyint('is_cut').default(0),
    parentLabelId: bigint('parent_label_id', { mode: 'number', unsigned: true }),
    labelType: tinyint('label_type').default(1),
    remainingWidth: decimal('remaining_width', { precision: 18, scale: 2 }),
    remainingLength: decimal('remaining_length', { precision: 18, scale: 2 }),
    status: tinyint('status').default(1),
    createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
    updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
    deleted: tinyint('deleted').default(0),
  },
  (t) => ({
    idxBatchNo: index('idx_batch_no').on(t.batchNo),
    idxLabelType: index('idx_label_type').on(t.labelType),
    idxMaterialCode: index('idx_material_code').on(t.materialCode),
    idxParentLabel: index('idx_parent_label').on(t.parentLabelId),
    idxWarehouse: index('idx_warehouse').on(t.warehouseId),
    pk: primaryKey({ columns: [t.id] }),
    ukLabelNo: uniqueIndex('uk_label_no').on(t.labelNo),
  })
);

export const invMaterialStd = mysqlTable(
  'inv_material_std',
  {
    id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
    materialCode: varchar('material_code', { length: 50 }).notNull(),
    materialName: varchar('material_name', { length: 100 }).notNull(),
    materialSpec: varchar('material_spec', { length: 200 }),
    unit: varchar('unit', { length: 20 }).notNull(),
    materialType: tinyint('material_type').notNull().default(1),
    categoryId: bigint('category_id', { mode: 'number', unsigned: true }),
    isBatch: tinyint('is_batch').notNull().default(1),
    isExpire: tinyint('is_expire').notNull().default(0),
    safeStock: decimal('safe_stock', { precision: 18, scale: 4 }).notNull().default('0.0000'),
    standardCost: decimal('standard_cost', { precision: 18, scale: 4 }).default('0.0000'),
    shelfLifeDays: int('shelf_life_days'),
    status: tinyint('status').notNull().default(1),
    remark: text('remark'),
    legacySource: varchar('legacy_source', { length: 30 }),
    legacyId: bigint('legacy_id', { mode: 'number', unsigned: true }),
    createTime: datetime('create_time')
      .notNull()
      .default(sql`CURRENT_TIMESTAMP`),
    updateTime: datetime('update_time')
      .notNull()
      .default(sql`CURRENT_TIMESTAMP`),
    createBy: bigint('create_by', { mode: 'number', unsigned: true }),
    updateBy: bigint('update_by', { mode: 'number', unsigned: true }),
    deleted: tinyint('deleted').notNull().default(0),
  },
  (t) => ({
    idxCategoryId: index('idx_category_id').on(t.categoryId),
    idxLegacy: index('idx_legacy').on(t.legacySource, t.legacyId),
    idxMaterialType: index('idx_material_type').on(t.materialType),
    idxStatus: index('idx_status').on(t.status),
    pk: primaryKey({ columns: [t.id] }),
    ukMaterialCode: uniqueIndex('uk_material_code').on(t.materialCode),
  })
);

export const invOutboundBatchAllocation = mysqlTable(
  'inv_outbound_batch_allocation',
  {
    id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
    sourceType: varchar('source_type', { length: 30 }).notNull(),
    sourceId: bigint('source_id', { mode: 'number', unsigned: true }).notNull(),
    sourceNo: varchar('source_no', { length: 50 }).notNull(),
    warehouseId: bigint('warehouse_id', { mode: 'number', unsigned: true }).notNull(),
    materialId: bigint('material_id', { mode: 'number', unsigned: true }).notNull(),
    batchId: bigint('batch_id', { mode: 'number', unsigned: true }).notNull(),
    batchNo: varchar('batch_no', { length: 50 }).notNull(),
    allocatedQty: decimal('allocated_qty', { precision: 18, scale: 4 }).notNull().default('0.0000'),
    unitCost: decimal('unit_cost', { precision: 18, scale: 4 }).default('0.0000'),
    totalCost: decimal('total_cost', { precision: 18, scale: 4 }).default('0.0000'),
    fifoMode: varchar('fifo_mode', { length: 20 }).default('fifo_auto'),
    operatorId: bigint('operator_id', { mode: 'number', unsigned: true }),
    operatorName: varchar('operator_name', { length: 50 }),
    createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  },
  (t) => ({
    idxBatch: index('idx_batch').on(t.batchId),
    idxCreateTime: index('idx_create_time').on(t.createTime),
    idxFifoMode: index('idx_fifo_mode').on(t.fifoMode),
    idxMaterial: index('idx_material').on(t.materialId),
    idxSource: index('idx_source').on(t.sourceType, t.sourceId),
    idxSourceNo: index('idx_source_no').on(t.sourceNo),
    idxWarehouse: index('idx_warehouse').on(t.warehouseId),
    pk: primaryKey({ columns: [t.id] }),
  })
);

export const invProductInventory = mysqlTable(
  'inv_product_inventory',
  {
    id: int('id').autoincrement().notNull(),
    productCode: varchar('product_code', { length: 100 }),
    productName: varchar('product_name', { length: 255 }),
    specification: varchar('specification', { length: 255 }),
    category: varchar('category', { length: 100 }),
    customer: varchar('customer', { length: 255 }),
    unit: varchar('unit', { length: 50 }),
    warehouse: varchar('warehouse', { length: 100 }),
    location: varchar('location', { length: 100 }),
    openingBalance: decimal('opening_balance', { precision: 18, scale: 4 }).default('0.0000'),
    totalIn: decimal('total_in', { precision: 18, scale: 4 }).default('0.0000'),
    totalOut: decimal('total_out', { precision: 18, scale: 4 }).default('0.0000'),
    currentBalance: decimal('current_balance', { precision: 18, scale: 4 }).default('0.0000'),
    batchNo: varchar('batch_no', { length: 100 }),
    supplier: varchar('supplier', { length: 255 }),
    sourceFile: varchar('source_file', { length: 255 }),
    sourceSheet: varchar('source_sheet', { length: 100 }),
    importTime: datetime('import_time').default(sql`CURRENT_TIMESTAMP`),
    remarks: text('remarks'),
  },
  (t) => ({
    idxCategory: index('idx_category').on(t.category),
    idxProductCode: index('idx_product_code').on(t.productCode),
    idxProductName: index('idx_product_name').on(t.productName),
    idxWarehouse: index('idx_warehouse').on(t.warehouse),
    pk: primaryKey({ columns: [t.id] }),
  })
);

// SKIP-FK (cross-domain): inv_production_inbound.workOrderId -> prd_work_order.id [SET NULL/undefined]
export const invProductionInbound = mysqlTable(
  'inv_production_inbound',
  {
    id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
    inboundNo: varchar('inbound_no', { length: 50 }).notNull(),
    workOrderId: bigint('work_order_id', { mode: 'number', unsigned: true }),
    workOrderNo: varchar('work_order_no', { length: 50 }),
    warehouseId: bigint('warehouse_id', { mode: 'number', unsigned: true }),
    inboundDate: date('inbound_date'),
    operatorName: varchar('operator_name', { length: 50 }),
    qcStatus: varchar('qc_status', { length: 20 }).default('pass'),
    status: tinyint('status').default(1),
    remark: varchar('remark', { length: 500 }),
    createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
    updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
    deleted: tinyint('deleted').notNull().default(0),
    createBy: bigint('create_by', { mode: 'number', unsigned: true }),
    updateBy: bigint('update_by', { mode: 'number', unsigned: true }),
  },
  (t) => ({
    idxWarehouseId: index('idx_warehouse_id').on(t.warehouseId),
    idxWorkOrderId: index('idx_work_order_id').on(t.workOrderId),
    pk: primaryKey({ columns: [t.id] }),
    ukInboundNo: uniqueIndex('uk_inbound_no').on(t.inboundNo),
    fkInvProdInboundWarehouse: foreignKey({
      columns: [t.warehouseId],
      foreignColumns: [invWarehouse.id],
    }),
    fk_prdWorkOrder_workOrderId: foreignKey({
      name: 'fk_inv_prod_inbound_workorder',
      columns: [t.workOrderId],
      foreignColumns: [prdWorkOrder.id],
    })
      .onDelete('set null')
      .onUpdate('cascade'),
  })
);

// SKIP-FK (cross-domain): inv_sales_outbound.customerId -> crm_customer.id [SET NULL/undefined]
// SKIP-FK (cross-domain): inv_sales_outbound.orderId -> sal_order.id [SET NULL/undefined]
export const invSalesOutbound = mysqlTable(
  'inv_sales_outbound',
  {
    id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
    outboundNo: varchar('outbound_no', { length: 50 }).notNull(),
    orderId: bigint('order_id', { mode: 'number', unsigned: true }),
    orderNo: varchar('order_no', { length: 50 }),
    customerId: bigint('customer_id', { mode: 'number', unsigned: true }),
    customerName: varchar('customer_name', { length: 100 }),
    warehouseId: bigint('warehouse_id', { mode: 'number', unsigned: true }),
    outboundDate: date('outbound_date'),
    deliveryPerson: varchar('delivery_person', { length: 50 }),
    status: tinyint('status').default(1),
    financePosted: tinyint('finance_posted').default(0),
    remark: varchar('remark', { length: 500 }),
    createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
    updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
    deleted: tinyint('deleted').notNull().default(0),
    createBy: bigint('create_by', { mode: 'number', unsigned: true }),
    updateBy: bigint('update_by', { mode: 'number', unsigned: true }),
  },
  (t) => ({
    idxCustomer: index('idx_customer').on(t.customerId),
    idxOrderId: index('idx_order_id').on(t.orderId),
    idxWarehouseId: index('idx_warehouse_id').on(t.warehouseId),
    pk: primaryKey({ columns: [t.id] }),
    ukOutboundNo: uniqueIndex('uk_outbound_no').on(t.outboundNo),
    fkInvSalesOutboundWarehouse: foreignKey({
      columns: [t.warehouseId],
      foreignColumns: [invWarehouse.id],
    }),
    fk_crmCustomer_customerId: foreignKey({
      name: 'fk_inv_sales_outbound_customer',
      columns: [t.customerId],
      foreignColumns: [crmCustomer.id],
    })
      .onDelete('set null')
      .onUpdate('cascade'),
    fk_salOrder_orderId: foreignKey({
      name: 'fk_inv_sales_outbound_order',
      columns: [t.orderId],
      foreignColumns: [salOrder.id],
    })
      .onDelete('set null')
      .onUpdate('cascade'),
  })
);

export const invScanLog = mysqlTable(
  'inv_scan_log',
  {
    id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
    scanType: varchar('scan_type', { length: 50 }).notNull(),
    qrContent: varchar('qr_content', { length: 500 }),
    labelNo: varchar('label_no', { length: 50 }),
    operation: varchar('operation', { length: 50 }),
    result: tinyint('result').default(1),
    message: varchar('message', { length: 500 }),
    operatorId: bigint('operator_id', { mode: 'number', unsigned: true }),
    operatorName: varchar('operator_name', { length: 50 }),
    scanTime: datetime('scan_time').default(sql`CURRENT_TIMESTAMP`),
    createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  },
  (t) => ({
    idxLabelNo: index('idx_label_no').on(t.labelNo),
    idxScanTime: index('idx_scan_time').on(t.scanTime),
    idxScanType: index('idx_scan_type').on(t.scanType),
    pk: primaryKey({ columns: [t.id] }),
  })
);

// SKIP-FK (cross-domain): inv_stock_adjust.approverId -> sys_user.id [SET NULL/undefined]
// SKIP-FK (cross-domain): inv_stock_adjust.operatorId -> sys_user.id [SET NULL/undefined]
export const invStockAdjust = mysqlTable(
  'inv_stock_adjust',
  {
    id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
    adjustNo: varchar('adjust_no', { length: 30 }).notNull(),
    warehouseId: bigint('warehouse_id', { mode: 'number', unsigned: true }).notNull(),
    adjustDate: date('adjust_date').notNull(),
    adjustType: tinyint('adjust_type').notNull().default(1),
    operatorId: bigint('operator_id', { mode: 'number', unsigned: true }),
    operatorName: varchar('operator_name', { length: 50 }),
    approverId: bigint('approver_id', { mode: 'number', unsigned: true }),
    approverName: varchar('approver_name', { length: 50 }),
    approveTime: datetime('approve_time'),
    status: tinyint('status').default(0),
    totalQty: decimal('total_qty', { precision: 18, scale: 4 }).default('0.0000'),
    totalAmount: decimal('total_amount', { precision: 18, scale: 4 }).default('0.0000'),
    version: int('version').default(0),
    remark: varchar('remark', { length: 500 }),
    deleted: tinyint('deleted').notNull().default(0),
    createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
    updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
    createBy: bigint('create_by', { mode: 'number', unsigned: true }),
    updateBy: bigint('update_by', { mode: 'number', unsigned: true }),
  },
  (t) => ({
    idxApprover: index('idx_approver').on(t.approverId),
    idxOperator: index('idx_operator').on(t.operatorId),
    idxStatus: index('idx_status').on(t.status),
    idxWarehouse: index('idx_warehouse').on(t.warehouseId),
    pk: primaryKey({ columns: [t.id] }),
    ukAdjustNo: uniqueIndex('uk_adjust_no').on(t.adjustNo),
    fkInvAdjustWarehouse: foreignKey({
      columns: [t.warehouseId],
      foreignColumns: [invWarehouse.id],
    }),
    fk_sysUser_approverId: foreignKey({
      name: 'fk_inv_adjust_approver',
      columns: [t.approverId],
      foreignColumns: [sysUser.id],
    })
      .onDelete('set null')
      .onUpdate('cascade'),
    fk_sysUser_operatorId: foreignKey({
      name: 'fk_inv_adjust_operator',
      columns: [t.operatorId],
      foreignColumns: [sysUser.id],
    })
      .onDelete('set null')
      .onUpdate('cascade'),
  })
);

export const invStocktakingItem = mysqlTable(
  'inv_stocktaking_item',
  {
    id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
    takingId: bigint('taking_id', { mode: 'number', unsigned: true }).notNull(),
    materialId: bigint('material_id', { mode: 'number', unsigned: true }).notNull(),
    materialCode: varchar('material_code', { length: 50 }),
    materialName: varchar('material_name', { length: 100 }),
    systemQty: decimal('system_qty', { precision: 18, scale: 4 }).default('0.0000'),
    actualQty: decimal('actual_qty', { precision: 18, scale: 4 }).default('0.0000'),
    diffQty: decimal('diff_qty', { precision: 18, scale: 4 }).default('0.0000'),
    unit: varchar('unit', { length: 20 }),
    batchNo: varchar('batch_no', { length: 50 }),
    batchId: bigint('batch_id', { mode: 'number', unsigned: true }),
    locationId: bigint('location_id', { mode: 'number', unsigned: true }),
    originalInboundDate: date('original_inbound_date'),
    qrCode: varchar('qr_code', { length: 100 }),
    remark: varchar('remark', { length: 255 }),
    createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
    updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
  },
  (t) => ({
    idxMaterial: index('idx_material').on(t.materialId),
    idxTaking: index('idx_taking').on(t.takingId),
    idxBatch: index('idx_batch').on(t.batchId),
    pk: primaryKey({ columns: [t.id] }),
    fkInvStocktakingItemMaterial: foreignKey({
      columns: [t.materialId],
      foreignColumns: [invMaterial.id],
    }),
    fkStocktakingItemTaking: foreignKey({
      columns: [t.takingId],
      foreignColumns: [invStocktaking.id],
    }),
  })
);

export const invTraceDetail = mysqlTable(
  'inv_trace_detail',
  {
    id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
    traceId: bigint('trace_id', { mode: 'number', unsigned: true }).notNull(),
    labelId: bigint('label_id', { mode: 'number', unsigned: true }).notNull(),
    labelNo: varchar('label_no', { length: 50 }).notNull(),
    materialCode: varchar('material_code', { length: 50 }),
    materialName: varchar('material_name', { length: 200 }),
    specification: varchar('specification', { length: 200 }),
    batchNo: varchar('batch_no', { length: 50 }),
    supplierName: varchar('supplier_name', { length: 200 }),
    receiveDate: date('receive_date'),
    materialType: tinyint('material_type').default(2),
    remark: varchar('remark', { length: 500 }),
    createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  },
  (t) => ({
    idxLabelId: index('idx_label_id').on(t.labelId),
    idxTraceId: index('idx_trace_id').on(t.traceId),
    pk: primaryKey({ columns: [t.id] }),
  })
);

export const invTraceRecord = mysqlTable(
  'inv_trace_record',
  {
    id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
    traceNo: varchar('trace_no', { length: 50 }).notNull(),
    cardId: bigint('card_id', { mode: 'number', unsigned: true }),
    cardNo: varchar('card_no', { length: 50 }),
    workOrderNo: varchar('work_order_no', { length: 50 }),
    productCode: varchar('product_code', { length: 50 }),
    mainLabelId: bigint('main_label_id', { mode: 'number', unsigned: true }),
    traceType: varchar('trace_type', { length: 20 }).default('production'),
    operatorId: bigint('operator_id', { mode: 'number', unsigned: true }),
    operatorName: varchar('operator_name', { length: 50 }),
    traceTime: datetime('trace_time').default(sql`CURRENT_TIMESTAMP`),
    remark: varchar('remark', { length: 500 }),
    deleted: tinyint('deleted').default(0),
    createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  },
  (t) => ({
    idxCardId: index('idx_card_id').on(t.cardId),
    idxDeleted: index('idx_deleted').on(t.deleted),
    idxMainLabel: index('idx_main_label').on(t.mainLabelId),
    pk: primaryKey({ columns: [t.id] }),
    ukTraceNo: uniqueIndex('uk_trace_no').on(t.traceNo),
  })
);

export const invTransferItem = mysqlTable(
  'inv_transfer_item',
  {
    id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
    transferId: bigint('transfer_id', { mode: 'number', unsigned: true }).notNull(),
    materialId: bigint('material_id', { mode: 'number', unsigned: true }).notNull(),
    materialCode: varchar('material_code', { length: 50 }),
    materialName: varchar('material_name', { length: 200 }),
    qrCode: varchar('qr_code', { length: 50 }),
    batchNo: varchar('batch_no', { length: 50 }),
    quantity: decimal('quantity', { precision: 18, scale: 4 }).notNull(),
    outQuantity: decimal('out_quantity', { precision: 18, scale: 4 }).default('0.0000'),
    inQuantity: decimal('in_quantity', { precision: 18, scale: 4 }).default('0.0000'),
    unit: varchar('unit', { length: 20 }),
    unitPrice: decimal('unit_price', { precision: 18, scale: 4 }).default('0.0000'),
    amount: decimal('amount', { precision: 18, scale: 4 }).default('0.0000'),
    remark: varchar('remark', { length: 255 }),
    deleted: tinyint('deleted').notNull().default(0),
    createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  },
  (t) => ({
    idxBatch: index('idx_batch').on(t.batchNo),
    idxMaterial: index('idx_material').on(t.materialId),
    idxTransfer: index('idx_transfer').on(t.transferId),
    pk: primaryKey({ columns: [t.id] }),
    fkInvTransferItemMaterial: foreignKey({
      columns: [t.materialId],
      foreignColumns: [invMaterial.id],
    }),
    fkTransferItemOrder: foreignKey({
      columns: [t.transferId],
      foreignColumns: [invTransferOrders.id],
    }),
  })
);

export const invUnitConversion = mysqlTable(
  'inv_unit_conversion',
  {
    id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
    materialId: bigint('material_id', { mode: 'number', unsigned: true }).notNull(),
    fromUnit: varchar('from_unit', { length: 20 }).notNull(),
    toUnit: varchar('to_unit', { length: 20 }).notNull(),
    ratio: decimal('ratio', { precision: 18, scale: 4 }).notNull(),
    isDefault: tinyint('is_default').default(0),
    remark: varchar('remark', { length: 255 }),
    deleted: tinyint('deleted').notNull().default(0),
    createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
    updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
    createBy: bigint('create_by', { mode: 'number', unsigned: true }),
    updateBy: bigint('update_by', { mode: 'number', unsigned: true }),
  },
  (t) => ({
    idxMaterial: index('idx_material').on(t.materialId),
    pk: primaryKey({ columns: [t.id] }),
    ukMaterialUnits: uniqueIndex('uk_material_units').on(t.materialId, t.fromUnit, t.toUnit),
    fkInvUnitConvMaterial: foreignKey({
      columns: [t.materialId],
      foreignColumns: [invMaterial.id],
    }),
  })
);

export const invWarehouseLog = mysqlTable(
  'inv_warehouse_log',
  {
    id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
    warehouseId: bigint('warehouse_id', { mode: 'number', unsigned: true }).notNull(),
    operationType: varchar('operation_type', { length: 30 }).notNull(),
    operationContent: text('operation_content'),
    operatorId: bigint('operator_id', { mode: 'number', unsigned: true }),
    operatorName: varchar('operator_name', { length: 50 }),
    createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  },
  (t) => ({
    idxCreateTime: index('idx_create_time').on(t.createTime),
    idxOperator: index('idx_operator').on(t.operatorId),
    idxWarehouse: index('idx_warehouse').on(t.warehouseId),
    pk: primaryKey({ columns: [t.id] }),
  })
);

export const invProductionInboundItem = mysqlTable(
  'inv_production_inbound_item',
  {
    id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
    inboundId: bigint('inbound_id', { mode: 'number', unsigned: true }).notNull(),
    materialId: bigint('material_id', { mode: 'number', unsigned: true }),
    materialCode: varchar('material_code', { length: 50 }),
    materialName: varchar('material_name', { length: 100 }),
    quantity: decimal('quantity', { precision: 18, scale: 3 }).notNull(),
    unit: varchar('unit', { length: 20 }),
    batchNo: varchar('batch_no', { length: 50 }),
    createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  },
  (t) => ({
    idxInboundId: index('idx_inbound_id').on(t.inboundId),
    pk: primaryKey({ columns: [t.id] }),
    fkInvProdInboundItemInbound: foreignKey({
      columns: [t.inboundId],
      foreignColumns: [invProductionInbound.id],
    }),
    fkInvProdInboundItemMaterial: foreignKey({
      columns: [t.materialId],
      foreignColumns: [invMaterial.id],
    }),
  })
);

export const invSalesOutboundItem = mysqlTable(
  'inv_sales_outbound_item',
  {
    id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
    outboundId: bigint('outbound_id', { mode: 'number', unsigned: true }).notNull(),
    materialId: bigint('material_id', { mode: 'number', unsigned: true }),
    materialCode: varchar('material_code', { length: 50 }),
    materialName: varchar('material_name', { length: 100 }),
    quantity: decimal('quantity', { precision: 18, scale: 3 }).notNull(),
    unit: varchar('unit', { length: 20 }),
    batchNo: varchar('batch_no', { length: 50 }),
    batchId: bigint('batch_id', { mode: 'number', unsigned: true }),
    locationId: bigint('location_id', { mode: 'number', unsigned: true }),
    qrCode: varchar('qr_code', { length: 100 }),
    originalInboundDate: date('original_inbound_date'),
    createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  },
  (t) => ({
    idxOutboundId: index('idx_outbound_id').on(t.outboundId),
    pk: primaryKey({ columns: [t.id] }),
    fkInvSalesOutboundItemMaterial: foreignKey({
      columns: [t.materialId],
      foreignColumns: [invMaterial.id],
    }),
    fkInvSalesOutboundItemOutbound: foreignKey({
      columns: [t.outboundId],
      foreignColumns: [invSalesOutbound.id],
    }),
    idxBatchId: index('idx_batch_id').on(t.batchId),
  })
);

export const invStockAdjustItem = mysqlTable(
  'inv_stock_adjust_item',
  {
    id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
    adjustId: bigint('adjust_id', { mode: 'number', unsigned: true }).notNull(),
    materialId: bigint('material_id', { mode: 'number', unsigned: true }).notNull(),
    materialCode: varchar('material_code', { length: 50 }),
    materialName: varchar('material_name', { length: 200 }),
    batchNo: varchar('batch_no', { length: 50 }),
    batchId: bigint('batch_id', { mode: 'number', unsigned: true }),
    locationId: bigint('location_id', { mode: 'number', unsigned: true }),
    originalInboundDate: date('original_inbound_date'),
    qrCode: varchar('qr_code', { length: 100 }),
    beforeQty: decimal('before_qty', { precision: 18, scale: 4 }).default('0.0000'),
    adjustQty: decimal('adjust_qty', { precision: 18, scale: 4 }).notNull(),
    afterQty: decimal('after_qty', { precision: 18, scale: 4 }).default('0.0000'),
    unit: varchar('unit', { length: 20 }),
    unitPrice: decimal('unit_price', { precision: 18, scale: 4 }).default('0.0000'),
    amount: decimal('amount', { precision: 18, scale: 4 }).default('0.0000'),
    reason: varchar('reason', { length: 255 }),
    deleted: tinyint('deleted').notNull().default(0),
    createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  },
  (t) => ({
    idxAdjust: index('idx_adjust').on(t.adjustId),
    idxMaterial: index('idx_material').on(t.materialId),
    idxBatch: index('idx_batch').on(t.batchId),
    pk: primaryKey({ columns: [t.id] }),
    fkInvAdjustItemAdjust: foreignKey({
      columns: [t.adjustId],
      foreignColumns: [invStockAdjust.id],
    }),
    fkInvAdjustItemMaterial: foreignKey({
      columns: [t.materialId],
      foreignColumns: [invMaterial.id],
    }),
  })
);
