// AUTO-GENERATED by scripts/_audit/gen_sys.cjs (2026-08-26)
// 来源: live information_schema. 建模 13 张核心 sys_* 缺失表。
// 跨域 FK / 自引用 FK 以注释保留；内部 sys_* FK 实写。
import { mysqlTable, int, bigint, smallint, mediumint, tinyint, varchar, char, decimal, float, double, text, date, datetime, timestamp, time, json, mysqlEnum, primaryKey, index, uniqueIndex, foreignKey } from 'drizzle-orm/mysql-core';
import { sql } from 'drizzle-orm';

export const sysAnnouncement = mysqlTable('sys_announcement', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  title: varchar('title', { length: 200 }).notNull(),
  content: text('content').notNull(),
  type: varchar('type', { length: 20 }).default('info'),
  priority: int('priority').default(0),
  isTop: tinyint('is_top').default(0),
  publishTime: datetime('publish_time'),
  expireTime: datetime('expire_time'),
  status: varchar('status', { length: 20 }).default('draft'),
  createBy: bigint('create_by', { mode: 'number', unsigned: true }),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  idxPublishTime: index('idx_publish_time').on(t.publishTime),
  idxStatus: index('idx_status').on(t.status),
  pk: primaryKey({ columns: [t.id] }),
}));

export const sysAnnouncementRead = mysqlTable('sys_announcement_read', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  announcementId: bigint('announcement_id', { mode: 'number', unsigned: true }).notNull(),
  userId: bigint('user_id', { mode: 'number', unsigned: true }).notNull(),
  readTime: datetime('read_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  idxUser: index('idx_user').on(t.userId),
  pk: primaryKey({ columns: [t.id] }),
  ukAnnouncementUser: uniqueIndex('uk_announcement_user').on(t.announcementId, t.userId),
}));

export const sysCalcParam = mysqlTable('sys_calc_param', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  category: varchar('category', { length: 50 }).notNull(),
  paramKey: varchar('param_key', { length: 100 }).notNull(),
  paramValue: varchar('param_value', { length: 500 }).notNull(),
  valueType: mysqlEnum('value_type', ['int', 'decimal', 'boolean', 'string'] as const).notNull().default('string'),
  defaultValue: varchar('default_value', { length: 500 }),
  description: varchar('description', { length: 500 }),
  status: tinyint('status').notNull().default(1),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
  createBy: bigint('create_by', { mode: 'number', unsigned: true }),
  updateBy: bigint('update_by', { mode: 'number', unsigned: true }),
  deleted: tinyint('deleted').notNull().default(0),
}, (t) => ({
  idxCategory: index('idx_category').on(t.category),
  idxStatus: index('idx_status').on(t.status),
  pk: primaryKey({ columns: [t.id] }),
  ukParamKey: uniqueIndex('uk_param_key').on(t.paramKey),
}));

export const sysCompany = mysqlTable('sys_company', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  fullName: varchar('full_name', { length: 200 }),
  companyName: varchar('company_name', { length: 100 }).notNull(),
  companyCode: varchar('company_code', { length: 50 }),
  address: varchar('address', { length: 255 }),
  phone: varchar('phone', { length: 50 }),
  email: varchar('email', { length: 100 }),
  logo: varchar('logo', { length: 255 }),
  status: tinyint('status').default(1),
  deleted: tinyint('deleted').default(0),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
  shortName: varchar('short_name', { length: 100 }),
  code: varchar('code', { length: 50 }),
  legalPerson: varchar('legal_person', { length: 50 }),
  regAddress: varchar('reg_address', { length: 500 }),
  contactPhone: varchar('contact_phone', { length: 50 }),
  taxNo: varchar('tax_no', { length: 50 }),
  baseCurrency: varchar('base_currency', { length: 10 }).default('CNY'),
  bankName: varchar('bank_name', { length: 100 }),
  bankAccount: varchar('bank_account', { length: 100 }),
  website: varchar('website', { length: 200 }),
  fax: varchar('fax', { length: 50 }),
  postcode: varchar('postcode', { length: 20 }),
  description: text('description'),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
}));

export const sysDictType = mysqlTable('sys_dict_type', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  dictName: varchar('dict_name', { length: 50 }).notNull(),
  dictCode: varchar('dict_code', { length: 50 }).notNull(),
  description: varchar('description', { length: 255 }),
  status: tinyint('status').default(1),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
  createBy: bigint('create_by', { mode: 'number', unsigned: true }),
  updateBy: bigint('update_by', { mode: 'number', unsigned: true }),
  deleted: tinyint('deleted').notNull().default(0),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
  ukDictCode: uniqueIndex('uk_dict_code').on(t.dictCode),
}));

export const sysEventProcessed = mysqlTable('sys_event_processed', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  eventId: bigint('event_id', { mode: 'number' }).notNull(),
  handlerName: varchar('handler_name', { length: 255 }).notNull(),
  status: varchar('status', { length: 20 }).notNull().default('processed'),
  processedAt: datetime('processed_at').notNull().default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  idxProcessedAt: index('idx_processed_at').on(t.processedAt),
  idxStatusProcessedAt: index('idx_status_processed_at').on(t.status, t.processedAt),
  pk: primaryKey({ columns: [t.id] }),
  ukEventHandler: uniqueIndex('uk_event_handler').on(t.eventId, t.handlerName),
}));

export const sysMigration = mysqlTable('sys_migration', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  migrationName: varchar('migration_name', { length: 255 }).notNull(),
  batch: int('batch').notNull().default(1),
  appliedAt: timestamp('applied_at').default(sql`CURRENT_TIMESTAMP`),
  executionTime: int('execution_time').default(0),
}, (t) => ({
  idxAppliedAt: index('idx_applied_at').on(t.appliedAt),
  idxMigrationName: index('idx_migration_name').on(t.migrationName),
  migrationName: uniqueIndex('migration_name').on(t.migrationName),
  pk: primaryKey({ columns: [t.id] }),
}));

export const sysNotice = mysqlTable('sys_notice', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  noticeTitle: varchar('notice_title', { length: 200 }).notNull(),
  noticeType: tinyint('notice_type').notNull(),
  noticeContent: text('notice_content'),
  status: tinyint('status').default(1),
  createBy: bigint('create_by', { mode: 'number', unsigned: true }),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
  remark: varchar('remark', { length: 500 }),
  deleted: tinyint('deleted').default(0),
}, (t) => ({
  pk: primaryKey({ columns: [t.id] }),
}));

export const sysOperLog = mysqlTable('sys_oper_log', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  title: varchar('title', { length: 50 }),
  businessType: tinyint('business_type').default(0),
  method: varchar('method', { length: 200 }),
  requestMethod: varchar('request_method', { length: 10 }),
  operatorType: tinyint('operator_type').default(0),
  operName: varchar('oper_name', { length: 50 }),
  operUrl: varchar('oper_url', { length: 500 }),
  operIp: varchar('oper_ip', { length: 128 }),
  operParam: text('oper_param'),
  jsonResult: text('json_result'),
  status: tinyint('status').default(1),
  errorMsg: text('error_msg'),
  operTime: datetime('oper_time').default(sql`CURRENT_TIMESTAMP`),
  costTime: bigint('cost_time', { mode: 'number' }).default(0),
}, (t) => ({
  idxBusinessType: index('idx_business_type').on(t.businessType),
  idxOperTime: index('idx_oper_time').on(t.operTime),
  pk: primaryKey({ columns: [t.id] }),
}));

export const sysOperationLog = mysqlTable('sys_operation_log', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  userId: bigint('user_id', { mode: 'number', unsigned: true }),
  username: varchar('username', { length: 50 }),
  operation: varchar('operation', { length: 100 }),
  method: varchar('method', { length: 10 }),
  requestUrl: varchar('request_url', { length: 500 }),
  requestParams: text('request_params'),
  responseData: text('response_data'),
  ip: varchar('ip', { length: 50 }),
  userAgent: varchar('user_agent', { length: 500 }),
  executeTime: int('execute_time'),
  status: tinyint('status'),
  errorMsg: text('error_msg'),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  businessId: varchar('business_id', { length: 100 }).default(''),
  businessType: varchar('business_type', { length: 50 }).default(''),
  responseResult: text('response_result'),
}, (t) => ({
  idxCreateTime: index('idx_create_time').on(t.createTime),
  idxOperLogTime: index('idx_oper_log_time').on(t.createTime),
  idxUser: index('idx_user').on(t.userId),
  pk: primaryKey({ columns: [t.id] }),
}));

export const sysScheduledTask = mysqlTable('sys_scheduled_task', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  taskName: varchar('task_name', { length: 200 }).notNull(),
  taskType: varchar('task_type', { length: 50 }).notNull(),
  taskGroup: varchar('task_group', { length: 50 }).default('default'),
  cronExpression: varchar('cron_expression', { length: 100 }),
  description: text('description'),
  config: text('config'),
  status: varchar('status', { length: 20 }).default('active'),
  lastExecuteTime: datetime('last_execute_time'),
  lastResult: text('last_result'),
  createBy: bigint('create_by', { mode: 'number', unsigned: true }),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  idxStatus: index('idx_status').on(t.status),
  idxTaskType: index('idx_task_type').on(t.taskType),
  pk: primaryKey({ columns: [t.id] }),
}));

export const sysTaskExecutionLog = mysqlTable('sys_task_execution_log', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  taskId: bigint('task_id', { mode: 'number', unsigned: true }).notNull(),
  taskName: varchar('task_name', { length: 200 }),
  startTime: datetime('start_time'),
  endTime: datetime('end_time'),
  status: varchar('status', { length: 20 }).default('running'),
  result: text('result'),
}, (t) => ({
  idxStatus: index('idx_status').on(t.status),
  idxTaskId: index('idx_task_id').on(t.taskId),
  pk: primaryKey({ columns: [t.id] }),
}));

export const sysDictData = mysqlTable('sys_dict_data', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  dictTypeId: bigint('dict_type_id', { mode: 'number', unsigned: true }).notNull(),
  dictLabel: varchar('dict_label', { length: 50 }).notNull(),
  dictValue: varchar('dict_value', { length: 100 }).notNull(),
  sortOrder: int('sort_order').default(0),
  status: tinyint('status').default(1),
  remark: varchar('remark', { length: 255 }),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
  createBy: bigint('create_by', { mode: 'number', unsigned: true }),
  updateBy: bigint('update_by', { mode: 'number', unsigned: true }),
  deleted: tinyint('deleted').notNull().default(0),
}, (t) => ({
  idxDictType: index('idx_dict_type').on(t.dictTypeId),
  idxStatus: index('idx_status').on(t.status),
  pk: primaryKey({ columns: [t.id] }),
  fkDictDataType: foreignKey({ columns: [t.dictTypeId], foreignColumns: [sysDictType.id] }),
}));

