// AUTO-GENERATED by scripts/_audit/gen_misc.cjs (2026-08-26)
// 域: biz ｜ 来源: live information_schema ｜ 建模 1 张核心缺失表。
// 导出名冲突自动规避（追加 Gen 后缀）；跨域 FK 注释保留；内部/已建模 FK 实写。
import { mysqlTable, int, bigint, smallint, mediumint, tinyint, varchar, char, decimal, float, double, text, date, datetime, timestamp, time, json, mysqlEnum, primaryKey, index, uniqueIndex, foreignKey } from 'drizzle-orm/mysql-core';
import { sql } from 'drizzle-orm';

export const bizContractReview = mysqlTable('biz_contract_review', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  reviewNo: varchar('review_no', { length: 50 }).notNull(),
  orderId: bigint('order_id', { mode: 'number', unsigned: true }),
  orderNo: varchar('order_no', { length: 50 }),
  customerId: bigint('customer_id', { mode: 'number', unsigned: true }),
  customerName: varchar('customer_name', { length: 100 }).default(''),
  productId: bigint('product_id', { mode: 'number', unsigned: true }),
  productCode: varchar('product_code', { length: 50 }),
  productName: varchar('product_name', { length: 200 }).default(''),
  quantity: decimal('quantity', { precision: 12, scale: 2 }).default('0.00'),
  amount: decimal('amount', { precision: 12, scale: 2 }).default('0.00'),
  deliveryDate: date('delivery_date'),
  sampleStatus: varchar('sample_status', { length: 20 }).default('pending'),
  qualityRequirement: text('quality_requirement'),
  productionCapacity: text('production_capacity'),
  materialAvailability: text('material_availability'),
  engineeringFeasibility: text('engineering_feasibility'),
  bizOpinion: text('biz_opinion'),
  engOpinion: text('eng_opinion'),
  qualityOpinion: text('quality_opinion'),
  prodOpinion: text('prod_opinion'),
  purchaseOpinion: text('purchase_opinion'),
  reviewDate: date('review_date'),
  status: tinyint('status').default(0),
  remark: text('remark'),
  deleted: tinyint('deleted').default(0),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
}, (t) => ({
  idxCustomer: index('idx_customer').on(t.customerId),
  idxStatus: index('idx_status').on(t.status),
  pk: primaryKey({ columns: [t.id] }),
  ukReviewNo: uniqueIndex('uk_review_no').on(t.reviewNo),
}));

