// AUTO-GENERATED by scripts/_audit/gen_misc.cjs (2026-08-26)
// 域: work ｜ 来源: live information_schema ｜ 建模 1 张核心缺失表。
// 导出名冲突自动规避（追加 Gen 后缀）；跨域 FK 注释保留；内部/已建模 FK 实写。
import { mysqlTable, int, bigint, smallint, mediumint, tinyint, varchar, char, decimal, float, double, text, date, datetime, timestamp, time, json, mysqlEnum, primaryKey, index, uniqueIndex, foreignKey } from 'drizzle-orm/mysql-core';
import { sql } from 'drizzle-orm';
import { prdWorkOrder } from './production';

export const workOrderCosts = mysqlTable('work_order_costs', {
  id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().notNull(),
  workOrderId: bigint('work_order_id', { mode: 'number', unsigned: true }).notNull(),
  workOrderNo: varchar('work_order_no', { length: 50 }),
  materialCost: decimal('material_cost', { precision: 18, scale: 4 }).default('0.0000'),
  laborCost: decimal('labor_cost', { precision: 18, scale: 4 }).default('0.0000'),
  manufacturingCost: decimal('manufacturing_cost', { precision: 18, scale: 4 }).default('0.0000'),
  totalCost: decimal('total_cost', { precision: 18, scale: 4 }).default('0.0000'),
  unitCost: decimal('unit_cost', { precision: 18, scale: 4 }).default('0.0000'),
  quantity: decimal('quantity', { precision: 18, scale: 4 }).default('0.0000'),
  calculateTime: datetime('calculate_time'),
  status: tinyint('status').default(0),
  createTime: datetime('create_time').default(sql`CURRENT_TIMESTAMP`),
  updateTime: datetime('update_time').default(sql`CURRENT_TIMESTAMP`),
  deleted: tinyint('deleted').notNull().default(0),
  createBy: bigint('create_by', { mode: 'number', unsigned: true }),
  updateBy: bigint('update_by', { mode: 'number', unsigned: true }),
}, (t) => ({
  idxStatus: index('idx_status').on(t.status),
  pk: primaryKey({ columns: [t.id] }),
  ukWorkOrder: uniqueIndex('uk_work_order').on(t.workOrderId),
  fkWoCostWorkOrder: foreignKey({ columns: [t.workOrderId], foreignColumns: [prdWorkOrder.id] }),
}));

