ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS login_fail_count INT DEFAULT 0 COMMENT '登录失败次数';
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS lock_time DATETIME DEFAULT NULL COMMENT '账号锁定时间';
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS last_login_time DATETIME DEFAULT NULL COMMENT '最后登录时间';
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS pwd_update_time DATETIME DEFAULT NULL COMMENT '密码修改时间';
