-- 057: 统一主键类型为 BIGINT UNSIGNED
-- 将 25 张使用 INT PK 的表改为 BIGINT UNSIGNED
-- 注意: 需先修改外键引用，再修改主键

-- ========================================
-- 阶段 1: 禁用外键检查
-- ========================================
SET FOREIGN_KEY_CHECKS = 0;

-- ========================================
-- 阶段 2: 修改主键列类型
-- ========================================

-- 仓库模块
ALTER TABLE inv_inbound_order MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE inv_inbound_item MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE inv_warehouse MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE inv_inventory MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE inv_outbound_order MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE inv_outbound_item MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE inv_transfer_order MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE inv_stocktaking MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT;

-- 销售模块
ALTER TABLE sal_order MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE sal_order_detail MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE sal_delivery MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE sal_return_order MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE sal_reconciliation MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE sal_quote MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE sal_quote_item MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT;

-- 采购模块
ALTER TABLE pur_purchase_order_line MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT;

-- 财务模块
ALTER TABLE fin_receivable MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE fin_payable MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT;

-- 生产模块
ALTER TABLE prd_work_order MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE prod_work_order MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE prod_work_order_item MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE prod_work_order_material_req MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT;

-- 打样模块
ALTER TABLE dcprint_sample_process_template MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE dcprint_sample_process_template_item MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE dcprint_sample_process_template_step MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT;

-- ========================================
-- 阶段 3: 重新启用外键检查
-- ========================================
SET FOREIGN_KEY_CHECKS = 1;
