-- 为 prd_standard_card 表添加缺失的字段
-- 运行此脚本更新数据库表结构

ALTER TABLE `prd_standard_card`
  ADD COLUMN `document_code` VARCHAR(50) COMMENT '文件编号' AFTER `date`,
  ADD COLUMN `spacing` VARCHAR(20) COMMENT '间距' AFTER `layout_type`,
  ADD COLUMN `spacing_value` VARCHAR(20) COMMENT '间距值' AFTER `spacing`,
  ADD COLUMN `sheet_width` VARCHAR(20) COMMENT '片材宽' AFTER `spacing_value`,
  ADD COLUMN `sheet_length` VARCHAR(20) COMMENT '片材长' AFTER `sheet_width`,
  ADD COLUMN `core_type` VARCHAR(50) COMMENT '纸芯类型' AFTER `sheet_length`,
  ADD COLUMN `paper_direction` VARCHAR(20) COMMENT '纸向' AFTER `core_type`,
  ADD COLUMN `roll_width` VARCHAR(20) COMMENT '料宽' AFTER `paper_direction`,
  ADD COLUMN `paper_edge` VARCHAR(20) COMMENT '纸边' AFTER `roll_width`,
  ADD COLUMN `standard_usage` VARCHAR(50) COMMENT '标准用量' AFTER `paper_edge`,
  ADD COLUMN `jump_distance` VARCHAR(20) COMMENT '跳距' AFTER `standard_usage`,
  ADD COLUMN `process_flow1` VARCHAR(100) COMMENT '工艺流程1' AFTER `jump_distance`,
  ADD COLUMN `process_flow2` VARCHAR(100) COMMENT '工艺流程2' AFTER `process_flow1`,
  ADD COLUMN `print_type` VARCHAR(50) COMMENT '表面处理' AFTER `process_flow2`,
  ADD COLUMN `first_jump_distance` VARCHAR(20) COMMENT '第一跳距' AFTER `print_type`,
  ADD COLUMN `sequences` JSON COMMENT '印序数据' AFTER `first_jump_distance`,
  ADD COLUMN `film_manufacturer` VARCHAR(100) COMMENT '膜厂商' AFTER `sequences`,
  ADD COLUMN `film_code` VARCHAR(50) COMMENT '膜编号' AFTER `film_manufacturer`,
  ADD COLUMN `film_size` VARCHAR(50) COMMENT '膜规格' AFTER `film_code`,
  ADD COLUMN `stamping_method` VARCHAR(50) COMMENT '冲压方法' AFTER `process_method`,
  ADD COLUMN `layout_method` VARCHAR(50) COMMENT '排版方式' AFTER `stamping_method`,
  ADD COLUMN `layout_way` VARCHAR(50) COMMENT '排版方向' AFTER `layout_method`,
  ADD COLUMN `jump_distance2` VARCHAR(20) COMMENT '跳距2' AFTER `layout_way`,
  ADD COLUMN `mylar_material` VARCHAR(100) COMMENT '麦拉材料' AFTER `jump_distance2`,
  ADD COLUMN `mylar_specs` VARCHAR(50) COMMENT '麦拉规格' AFTER `mylar_material`,
  ADD COLUMN `mylar_layout` VARCHAR(50) COMMENT '麦拉排版' AFTER `mylar_specs`,
  ADD COLUMN `mylar_jump` VARCHAR(20) COMMENT '麦拉跳距' AFTER `mylar_layout`,
  ADD COLUMN `adhesive_type` VARCHAR(50) COMMENT '背胶种类' AFTER `mylar_jump`,
  ADD COLUMN `adhesive_manufacturer` VARCHAR(100) COMMENT '背胶厂商' AFTER `adhesive_type`,
  ADD COLUMN `adhesive_code` VARCHAR(50) COMMENT '背胶编号' AFTER `adhesive_manufacturer`,
  ADD COLUMN `adhesive_size` VARCHAR(50) COMMENT '背胶尺寸' AFTER `adhesive_code`,
  ADD COLUMN `dashed_knife` TINYINT DEFAULT 0 COMMENT '加虚线刀: 0-否, 1-是' AFTER `adhesive_size`,
  ADD COLUMN `slice_per_row` VARCHAR(20) COMMENT 'PCS/排' AFTER `dashed_knife`,
  ADD COLUMN `slice_per_roll` VARCHAR(20) COMMENT 'PCS/卷' AFTER `slice_per_row`,
  ADD COLUMN `slice_per_bundle` VARCHAR(20) COMMENT 'PCS/扎' AFTER `slice_per_roll`,
  ADD COLUMN `slice_per_bag` VARCHAR(20) COMMENT 'PCS/袋' AFTER `slice_per_bundle`,
  ADD COLUMN `slice_per_box` VARCHAR(20) COMMENT 'PCS/箱' AFTER `slice_per_bag`,
  ADD COLUMN `back_knife_mold` VARCHAR(50) COMMENT '背胶刀模存放' AFTER `slice_per_box`,
  ADD COLUMN `back_mylar_mold` VARCHAR(50) COMMENT '背麦拉刀模存放' AFTER `back_knife_mold`,
  ADD COLUMN `release_paper_code` VARCHAR(50) COMMENT '离型纸编号' AFTER `back_mylar_mold`,
  ADD COLUMN `release_paper_type` VARCHAR(50) COMMENT '离型纸种类' AFTER `release_paper_code`,
  ADD COLUMN `release_paper_specs` VARCHAR(50) COMMENT '离型纸规格' AFTER `release_paper_type`,
  ADD COLUMN `padding_material` VARCHAR(100) COMMENT '填充材料' AFTER `release_paper_specs`,
  ADD COLUMN `packing_material` VARCHAR(100) COMMENT '包装材料' AFTER `padding_material`,
  ADD COLUMN `special_color` VARCHAR(200) COMMENT '专色配比' AFTER `packing_material`,
  ADD COLUMN `color_formula` VARCHAR(200) COMMENT '颜色配方' AFTER `special_color`,
  ADD COLUMN `file_path` VARCHAR(200) COMMENT '电脑图档存储路径' AFTER `color_formula`,
  ADD COLUMN `sample_info` VARCHAR(200) COMMENT '样品信息' AFTER `file_path`,
  ADD COLUMN `notes` TEXT COMMENT '注意事项' AFTER `sample_info`,
  ADD COLUMN `creator` VARCHAR(50) COMMENT '制作' AFTER `notes`,
  ADD COLUMN `reviewer` VARCHAR(50) COMMENT '审核' AFTER `creator`,
  ADD COLUMN `factory_manager` VARCHAR(50) COMMENT '厂长' AFTER `reviewer`,
  ADD COLUMN `quality_manager` VARCHAR(50) COMMENT '品管' AFTER `factory_manager`,
  ADD COLUMN `sales` VARCHAR(50) COMMENT '业务' AFTER `quality_manager`,
  ADD COLUMN `approver` VARCHAR(50) COMMENT '核准' AFTER `sales`;

-- 注意：如果 print_type 和 process_method 列已存在但注释不对，可以使用以下语句修改
-- ALTER TABLE `prd_standard_card` MODIFY COLUMN `print_type` VARCHAR(50) COMMENT '表面处理';
-- ALTER TABLE `prd_standard_card` MODIFY COLUMN `process_method` VARCHAR(50) COMMENT '工艺方式';
